/* 人造石（壓克力系 Solid Surface）色板：LG HIMACS（lxhausys.com 歐洲色卡）、LOTTE Staron（staron.com 台灣色卡）、杜邦可麗耐 Corian（colors.corian.com 北美色卡），2026/10 下載；640x400 貼圖在 swatches/himacs|staron|corian/、縮圖在 thumb/
   單價為暫定參考（人造石行情 80～150 元/cm ≈ 1,200～2,300 元/才，Corian 較高），請於「板材售價」修改；台灣實際供應色號請向代理商確認 */
window.SWATCHES = (window.SWATCHES || []).concat([
{
"code": "S028E",
"name": "Alpine White S028E",
"en": "HIMACS Solids　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Solids",
"hex": "#ffffff",
"img": "swatches/himacs/hm_S028E.jpg",
"thumb": "swatches/himacs/thumb/hm_S028E.jpg",
"price": 1500,
"top": true
},
{
"code": "S236",
"name": "Lafayette green",
"en": "HIMACS Solids　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Solids",
"hex": "#788375",
"img": "swatches/himacs/hm_S236.jpg",
"thumb": "swatches/himacs/thumb/hm_S236.jpg",
"price": 1500,
"top": true
},
{
"code": "S235",
"name": "Urban Sage",
"en": "HIMACS Solids　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Solids",
"hex": "#b6c9ad",
"img": "swatches/himacs/hm_S235.jpg",
"thumb": "swatches/himacs/thumb/hm_S235.jpg",
"price": 1500,
"top": true
},
{
"code": "S002",
"name": "Almond",
"en": "HIMACS Solids　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Solids",
"hex": "#e0d8c1",
"img": "swatches/himacs/hm_S002.jpg",
"thumb": "swatches/himacs/thumb/hm_S002.jpg",
"price": 1500,
"top": true
},
{
"code": "S028",
"name": "Alpine White S028",
"en": "HIMACS Solids　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Solids",
"hex": "#fdfef8",
"img": "swatches/himacs/hm_S028.jpg",
"thumb": "swatches/himacs/thumb/hm_S028.jpg",
"price": 1500,
"top": true
},
{
"code": "S006",
"name": "Arctic White",
"en": "HIMACS Solids　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Solids",
"hex": "#fbfbf9",
"img": "swatches/himacs/hm_S006.jpg",
"thumb": "swatches/himacs/thumb/hm_S006.jpg",
"price": 1500,
"top": true
},
{
"code": "S102",
"name": "Babylon Beige",
"en": "HIMACS Solids　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Solids",
"hex": "#c2b79c",
"img": "swatches/himacs/hm_S102.jpg",
"thumb": "swatches/himacs/thumb/hm_S102.jpg",
"price": 1500,
"top": true
},
{
"code": "S026",
"name": "Banana",
"en": "HIMACS Solids　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Solids",
"hex": "#f3d24f",
"img": "swatches/himacs/hm_S026.jpg",
"thumb": "swatches/himacs/thumb/hm_S026.jpg",
"price": 1500,
"top": true
},
{
"code": "S100",
"name": "Coffee Brown",
"en": "HIMACS Solids　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Solids",
"hex": "#1f0d09",
"img": "swatches/himacs/hm_S100.jpg",
"thumb": "swatches/himacs/thumb/hm_S100.jpg",
"price": 1500,
"top": true
},
{
"code": "S009",
"name": "Cream",
"en": "HIMACS Solids　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Solids",
"hex": "#fdfae9",
"img": "swatches/himacs/hm_S009.jpg",
"thumb": "swatches/himacs/thumb/hm_S009.jpg",
"price": 1500,
"top": true
},
{
"code": "S034",
"name": "Diamond White",
"en": "HIMACS Solids　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Solids",
"hex": "#ffffff",
"img": "swatches/himacs/hm_S034.jpg",
"thumb": "swatches/himacs/thumb/hm_S034.jpg",
"price": 1500,
"top": true
},
{
"code": "S119",
"name": "Evergreen",
"en": "HIMACS Solids　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Solids",
"hex": "#0a3933",
"img": "swatches/himacs/hm_S119.jpg",
"thumb": "swatches/himacs/thumb/hm_S119.jpg",
"price": 1500,
"top": true
},
{
"code": "S025",
"name": "Fiery Red",
"en": "HIMACS Solids　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Solids",
"hex": "#af2729",
"img": "swatches/himacs/hm_S025.jpg",
"thumb": "swatches/himacs/thumb/hm_S025.jpg",
"price": 1500,
"top": true
},
{
"code": "S005",
"name": "Grey",
"en": "HIMACS Solids　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Solids",
"hex": "#d6d3cc",
"img": "swatches/himacs/hm_S005.jpg",
"thumb": "swatches/himacs/thumb/hm_S005.jpg",
"price": 1500,
"top": true
},
{
"code": "S029",
"name": "Ivory White",
"en": "HIMACS Solids　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Solids",
"hex": "#fbfbf3",
"img": "swatches/himacs/hm_S029.jpg",
"thumb": "swatches/himacs/thumb/hm_S029.jpg",
"price": 1500,
"top": true
},
{
"code": "S117",
"name": "Midnight Grey",
"en": "HIMACS Solids　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Solids",
"hex": "#2d2e2e",
"img": "swatches/himacs/hm_S117.jpg",
"thumb": "swatches/himacs/thumb/hm_S117.jpg",
"price": 1500,
"top": true
},
{
"code": "S201",
"name": "Nougat Cream",
"en": "HIMACS Solids　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Solids",
"hex": "#fbf2e1",
"img": "swatches/himacs/hm_S201.jpg",
"thumb": "swatches/himacs/thumb/hm_S201.jpg",
"price": 1500,
"top": true
},
{
"code": "S027",
"name": "Orange",
"en": "HIMACS Solids　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Solids",
"hex": "#e16b14",
"img": "swatches/himacs/hm_S027.jpg",
"thumb": "swatches/himacs/thumb/hm_S027.jpg",
"price": 1500,
"top": true
},
{
"code": "S233",
"name": "Pink Leia",
"en": "HIMACS Solids　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Solids",
"hex": "#f3d3d8",
"img": "swatches/himacs/hm_S233.jpg",
"thumb": "swatches/himacs/thumb/hm_S233.jpg",
"price": 1500,
"top": true
},
{
"code": "S001",
"name": "Satin White",
"en": "HIMACS Solids　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Solids",
"hex": "#f2efe8",
"img": "swatches/himacs/hm_S001.jpg",
"thumb": "swatches/himacs/thumb/hm_S001.jpg",
"price": 1500,
"top": true
},
{
"code": "W001",
"name": "Ice Queen",
"en": "HIMACS Lucia　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Lucia",
"hex": "#fbfafa",
"img": "swatches/himacs/hm_W001.jpg",
"thumb": "swatches/himacs/thumb/hm_W001.jpg",
"price": 1500,
"top": true
},
{
"code": "W003",
"name": "Shadow Queen",
"en": "HIMACS Lucia　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Lucia",
"hex": "#b2b1b3",
"img": "swatches/himacs/hm_W003.jpg",
"thumb": "swatches/himacs/thumb/hm_W003.jpg",
"price": 1500,
"top": true
},
{
"code": "W004",
"name": "Star Queen",
"en": "HIMACS Lucia　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Lucia",
"hex": "#101010",
"img": "swatches/himacs/hm_W004.jpg",
"thumb": "swatches/himacs/thumb/hm_W004.jpg",
"price": 1500,
"top": true
},
{
"code": "S305",
"name": "Emerald",
"en": "HIMACS Lucent　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Lucent",
"hex": "#9dd0c1",
"img": "swatches/himacs/hm_S305.jpg",
"thumb": "swatches/himacs/thumb/hm_S305.jpg",
"price": 1500,
"top": true
},
{
"code": "S302",
"name": "Opal",
"en": "HIMACS Lucent　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Lucent",
"hex": "#ffffff",
"img": "swatches/himacs/hm_S302.jpg",
"thumb": "swatches/himacs/thumb/hm_S302.jpg",
"price": 1500,
"top": true
},
{
"code": "S304",
"name": "Ruby",
"en": "HIMACS Lucent　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Lucent",
"hex": "#f6e7ee",
"img": "swatches/himacs/hm_S304.jpg",
"thumb": "swatches/himacs/thumb/hm_S304.jpg",
"price": 1500,
"top": true
},
{
"code": "S303",
"name": "Sapphire",
"en": "HIMACS Lucent　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Lucent",
"hex": "#c1d6e6",
"img": "swatches/himacs/hm_S303.jpg",
"thumb": "swatches/himacs/thumb/hm_S303.jpg",
"price": 1500,
"top": true
},
{
"code": "GM05",
"name": "Gravilla Charcoal",
"en": "HIMACS Gravilla　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Gravilla",
"hex": "#222222",
"img": "swatches/himacs/hm_GM05.jpg",
"thumb": "swatches/himacs/thumb/hm_GM05.jpg",
"price": 1500,
"top": true
},
{
"code": "GM02",
"name": "Gravilla cream",
"en": "HIMACS Gravilla　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Gravilla",
"hex": "#edeae2",
"img": "swatches/himacs/hm_GM02.jpg",
"thumb": "swatches/himacs/thumb/hm_GM02.jpg",
"price": 1500,
"top": true
},
{
"code": "GM03",
"name": "Gravilla Millstone",
"en": "HIMACS Gravilla　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Gravilla",
"hex": "#e3ddd7",
"img": "swatches/himacs/hm_GM03.jpg",
"thumb": "swatches/himacs/thumb/hm_GM03.jpg",
"price": 1500,
"top": true
},
{
"code": "GM01",
"name": "Gravilla snow",
"en": "HIMACS Gravilla　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Gravilla",
"hex": "#f9f6f1",
"img": "swatches/himacs/hm_GM01.jpg",
"thumb": "swatches/himacs/thumb/hm_GM01.jpg",
"price": 1500,
"top": true
},
{
"code": "VW01",
"name": "Gemini",
"en": "HIMACS Volcanics　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Volcanics",
"hex": "#f6f5f3",
"img": "swatches/himacs/hm_VW01.jpg",
"thumb": "swatches/himacs/thumb/hm_VW01.jpg",
"price": 1500,
"top": true
},
{
"code": "VG21",
"name": "Maui",
"en": "HIMACS Volcanics　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Volcanics",
"hex": "#2a3e39",
"img": "swatches/himacs/hm_VG21.jpg",
"thumb": "swatches/himacs/thumb/hm_VG21.jpg",
"price": 1500,
"top": true
},
{
"code": "VA01",
"name": "Santa Ana",
"en": "HIMACS Volcanics　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Volcanics",
"hex": "#d2d0c4",
"img": "swatches/himacs/hm_VA01.jpg",
"thumb": "swatches/himacs/thumb/hm_VA01.jpg",
"price": 1500,
"top": true
},
{
"code": "VE01",
"name": "Tambora",
"en": "HIMACS Volcanics　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Volcanics",
"hex": "#e2dccf",
"img": "swatches/himacs/hm_VE01.jpg",
"thumb": "swatches/himacs/thumb/hm_VE01.jpg",
"price": 1500,
"top": true
},
{
"code": "MW01",
"name": "Aurora Alps",
"en": "HIMACS Aurora & Marmo　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Aurora & Marmo",
"hex": "#f8f5ef",
"img": "swatches/himacs/hm_MW01.jpg",
"thumb": "swatches/himacs/thumb/hm_MW01.jpg",
"price": 1500,
"top": true
},
{
"code": "M630",
"name": "Aurora Nero",
"en": "HIMACS Aurora & Marmo　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Aurora & Marmo",
"hex": "#26272b",
"img": "swatches/himacs/hm_M630.jpg",
"thumb": "swatches/himacs/thumb/hm_M630.jpg",
"price": 1500,
"top": true
},
{
"code": "M629",
"name": "Aurora Pluma",
"en": "HIMACS Aurora & Marmo　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Aurora & Marmo",
"hex": "#fbf8f0",
"img": "swatches/himacs/hm_M629.jpg",
"thumb": "swatches/himacs/thumb/hm_M629.jpg",
"price": 1500,
"top": true
},
{
"code": "M633",
"name": "Aurora Sage",
"en": "HIMACS Aurora & Marmo　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Aurora & Marmo",
"hex": "#d7d8d2",
"img": "swatches/himacs/hm_M633.jpg",
"thumb": "swatches/himacs/thumb/hm_M633.jpg",
"price": 1500,
"top": true
},
{
"code": "M706",
"name": "Aurora Angora",
"en": "HIMACS Aurora & Marmo　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Aurora & Marmo",
"hex": "#dfdacb",
"img": "swatches/himacs/hm_M706.jpg",
"thumb": "swatches/himacs/thumb/hm_M706.jpg",
"price": 1500,
"top": true
},
{
"code": "M606",
"name": "Aurora Bianco",
"en": "HIMACS Aurora & Marmo　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Aurora & Marmo",
"hex": "#f9f8f7",
"img": "swatches/himacs/hm_M606.jpg",
"thumb": "swatches/himacs/thumb/hm_M606.jpg",
"price": 1500,
"top": true
},
{
"code": "M612",
"name": "Aurora Bisque",
"en": "HIMACS Aurora & Marmo　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Aurora & Marmo",
"hex": "#eae0d0",
"img": "swatches/himacs/hm_M612.jpg",
"thumb": "swatches/himacs/thumb/hm_M612.jpg",
"price": 1500,
"top": true
},
{
"code": "M617",
"name": "Aurora Blanc",
"en": "HIMACS Aurora & Marmo　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Aurora & Marmo",
"hex": "#f2efee",
"img": "swatches/himacs/hm_M617.jpg",
"thumb": "swatches/himacs/thumb/hm_M617.jpg",
"price": 1500,
"top": true
},
{
"code": "M627",
"name": "Aurora Butter Cream",
"en": "HIMACS Aurora & Marmo　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Aurora & Marmo",
"hex": "#dbd0ba",
"img": "swatches/himacs/hm_M627.jpg",
"thumb": "swatches/himacs/thumb/hm_M627.jpg",
"price": 1500,
"top": true
},
{
"code": "M705",
"name": "Aurora Canyon",
"en": "HIMACS Aurora & Marmo　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Aurora & Marmo",
"hex": "#e1dbca",
"img": "swatches/himacs/hm_M705.jpg",
"thumb": "swatches/himacs/thumb/hm_M705.jpg",
"price": 1500,
"top": true
},
{
"code": "M615",
"name": "Aurora Cotton",
"en": "HIMACS Aurora & Marmo　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Aurora & Marmo",
"hex": "#e9e6e0",
"img": "swatches/himacs/hm_M615.jpg",
"thumb": "swatches/himacs/thumb/hm_M615.jpg",
"price": 1500,
"top": true
},
{
"code": "M628",
"name": "Aurora Daymoon",
"en": "HIMACS Aurora & Marmo　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Aurora & Marmo",
"hex": "#e9e6e4",
"img": "swatches/himacs/hm_M628.jpg",
"thumb": "swatches/himacs/thumb/hm_M628.jpg",
"price": 1500,
"top": true
},
{
"code": "M701",
"name": "Aurora Ecru",
"en": "HIMACS Aurora & Marmo　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Aurora & Marmo",
"hex": "#f1efed",
"img": "swatches/himacs/hm_M701.jpg",
"thumb": "swatches/himacs/thumb/hm_M701.jpg",
"price": 1500,
"top": true
},
{
"code": "M702",
"name": "Aurora Frost",
"en": "HIMACS Aurora & Marmo　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Aurora & Marmo",
"hex": "#fbfaf8",
"img": "swatches/himacs/hm_M702.jpg",
"thumb": "swatches/himacs/thumb/hm_M702.jpg",
"price": 1500,
"top": true
},
{
"code": "M608",
"name": "Aurora Grey",
"en": "HIMACS Aurora & Marmo　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Aurora & Marmo",
"hex": "#e8e5e0",
"img": "swatches/himacs/hm_M608.jpg",
"thumb": "swatches/himacs/thumb/hm_M608.jpg",
"price": 1500,
"top": true
},
{
"code": "M623",
"name": "Aurora Linen Cream",
"en": "HIMACS Aurora & Marmo　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Aurora & Marmo",
"hex": "#f2ece1",
"img": "swatches/himacs/hm_M623.jpg",
"thumb": "swatches/himacs/thumb/hm_M623.jpg",
"price": 1500,
"top": true
},
{
"code": "M707",
"name": "Aurora Magnolia",
"en": "HIMACS Aurora & Marmo　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Aurora & Marmo",
"hex": "#f1f0ee",
"img": "swatches/himacs/hm_M707.jpg",
"thumb": "swatches/himacs/thumb/hm_M707.jpg",
"price": 1500,
"top": true
},
{
"code": "M703",
"name": "Aurora Midnight",
"en": "HIMACS Aurora & Marmo　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Aurora & Marmo",
"hex": "#121212",
"img": "swatches/himacs/hm_M703.jpg",
"thumb": "swatches/himacs/thumb/hm_M703.jpg",
"price": 1500,
"top": true
},
{
"code": "M626",
"name": "Aurora Modern Grey",
"en": "HIMACS Aurora & Marmo　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Aurora & Marmo",
"hex": "#e7e6e2",
"img": "swatches/himacs/hm_M626.jpg",
"thumb": "swatches/himacs/thumb/hm_M626.jpg",
"price": 1500,
"top": true
},
{
"code": "M704",
"name": "Aurora Stone Grey",
"en": "HIMACS Aurora & Marmo　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Aurora & Marmo",
"hex": "#d7d0c5",
"img": "swatches/himacs/hm_M704.jpg",
"thumb": "swatches/himacs/thumb/hm_M704.jpg",
"price": 1500,
"top": true
},
{
"code": "M816",
"name": "Calacatta Desert Moon",
"en": "HIMACS Calacatta　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Calacatta",
"hex": "#f6f0e4",
"img": "swatches/himacs/hm_M816.jpg",
"thumb": "swatches/himacs/thumb/hm_M816.jpg",
"price": 1500,
"top": true
},
{
"code": "M815",
"name": "Calacatta Lake Moon",
"en": "HIMACS Calacatta　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Calacatta",
"hex": "#f6f5f3",
"img": "swatches/himacs/hm_M815.jpg",
"thumb": "swatches/himacs/thumb/hm_M815.jpg",
"price": 1500,
"top": true
},
{
"code": "M831",
"name": "Calacatta Vista",
"en": "HIMACS Calacatta　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Calacatta",
"hex": "#fbfcf6",
"img": "swatches/himacs/hm_M831.jpg",
"thumb": "swatches/himacs/thumb/hm_M831.jpg",
"price": 1500,
"top": true
},
{
"code": "M802L",
"name": "Calacatta Fiore",
"en": "HIMACS Calacatta　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Calacatta",
"hex": "#fbfcf7",
"img": "swatches/himacs/hm_M802L.jpg",
"thumb": "swatches/himacs/thumb/hm_M802L.jpg",
"price": 1500,
"top": true
},
{
"code": "M801",
"name": "Calacatta Luna",
"en": "HIMACS Calacatta　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Calacatta",
"hex": "#f6f6f5",
"img": "swatches/himacs/hm_M801.jpg",
"thumb": "swatches/himacs/thumb/hm_M801.jpg",
"price": 1500,
"top": true
},
{
"code": "M803",
"name": "Calacatta Ramo",
"en": "HIMACS Calacatta　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Calacatta",
"hex": "#f6f6f8",
"img": "swatches/himacs/hm_M803.jpg",
"thumb": "swatches/himacs/thumb/hm_M803.jpg",
"price": 1500,
"top": true
},
{
"code": "M551",
"name": "Chic Concrete",
"en": "HIMACS Concrete　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Concrete",
"hex": "#a29b8b",
"img": "swatches/himacs/hm_M551.jpg",
"thumb": "swatches/himacs/thumb/hm_M551.jpg",
"price": 1500,
"top": true
},
{
"code": "G557",
"name": "Cloud Concrete",
"en": "HIMACS Concrete　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Concrete",
"hex": "#d9d7ca",
"img": "swatches/himacs/hm_G557.jpg",
"thumb": "swatches/himacs/thumb/hm_G557.jpg",
"price": 1500,
"top": true
},
{
"code": "M553",
"name": "Ebony Concrete",
"en": "HIMACS Concrete　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Concrete",
"hex": "#434240",
"img": "swatches/himacs/hm_M553.jpg",
"thumb": "swatches/himacs/thumb/hm_M553.jpg",
"price": 1500,
"top": true
},
{
"code": "M552",
"name": "Shadow Concrete",
"en": "HIMACS Concrete　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Concrete",
"hex": "#7d7977",
"img": "swatches/himacs/hm_M552.jpg",
"thumb": "swatches/himacs/thumb/hm_M552.jpg",
"price": 1500,
"top": true
},
{
"code": "G556",
"name": "Snow Concrete",
"en": "HIMACS Concrete　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Concrete",
"hex": "#eae9e2",
"img": "swatches/himacs/hm_G556.jpg",
"thumb": "swatches/himacs/thumb/hm_G556.jpg",
"price": 1500,
"top": true
},
{
"code": "G554",
"name": "Urban Concrete",
"en": "HIMACS Concrete　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Concrete",
"hex": "#a79f92",
"img": "swatches/himacs/hm_G554.jpg",
"thumb": "swatches/himacs/thumb/hm_G554.jpg",
"price": 1500,
"top": true
},
{
"code": "Q106",
"name": "Terrazzo Marsala",
"en": "HIMACS Terrazzo　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Terrazzo",
"hex": "#fbf9f8",
"img": "swatches/himacs/hm_Q106.jpg",
"thumb": "swatches/himacs/thumb/hm_Q106.jpg",
"price": 1500,
"top": true
},
{
"code": "Q103",
"name": "Terrazzo Nuvola",
"en": "HIMACS Terrazzo　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Terrazzo",
"hex": "#f2efe6",
"img": "swatches/himacs/hm_Q103.jpg",
"thumb": "swatches/himacs/thumb/hm_Q103.jpg",
"price": 1500,
"top": true
},
{
"code": "Q107",
"name": "Terrazzo Selva",
"en": "HIMACS Terrazzo　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Terrazzo",
"hex": "#393437",
"img": "swatches/himacs/hm_Q107.jpg",
"thumb": "swatches/himacs/thumb/hm_Q107.jpg",
"price": 1500,
"top": true
},
{
"code": "Q105",
"name": "Terrazzo Sorrento",
"en": "HIMACS Terrazzo　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Terrazzo",
"hex": "#f9f7f5",
"img": "swatches/himacs/hm_Q105.jpg",
"thumb": "swatches/himacs/thumb/hm_Q105.jpg",
"price": 1500,
"top": true
},
{
"code": "Q102",
"name": "Terrazzo Ulivo",
"en": "HIMACS Terrazzo　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Terrazzo",
"hex": "#e8e6de",
"img": "swatches/himacs/hm_Q102.jpg",
"thumb": "swatches/himacs/thumb/hm_Q102.jpg",
"price": 1500,
"top": true
},
{
"code": "Q001",
"name": "Terrazzo Classico",
"en": "HIMACS Terrazzo　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Terrazzo",
"hex": "#d7d3c9",
"img": "swatches/himacs/hm_Q001.jpg",
"thumb": "swatches/himacs/thumb/hm_Q001.jpg",
"price": 1500,
"top": true
},
{
"code": "P001",
"name": "Perna White",
"en": "HIMACS Granite, Perna, Quartz, Sand & Pearl　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Granite, Perna, Quartz, Sand & Pearl",
"hex": "#f7f7f4",
"img": "swatches/himacs/hm_P001.jpg",
"thumb": "swatches/himacs/thumb/hm_P001.jpg",
"price": 1500,
"top": true
},
{
"code": "S728",
"name": "Alpine White-FR",
"en": "HIMACS Advanced Series　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Advanced Series",
"hex": "#fdfef8",
"img": "swatches/himacs/hm_S728.jpg",
"thumb": "swatches/himacs/thumb/hm_S728.jpg",
"price": 1500,
"top": true
},
{
"code": "S828",
"name": "Alpine White-UV+",
"en": "HIMACS Advanced Series　人造石（壓克力系）　官網未標價，暫定 1,500 元/才",
"brand": "LG HIMACS",
"series": "Advanced Series",
"hex": "#fdfef8",
"img": "swatches/himacs/hm_S828.jpg",
"thumb": "swatches/himacs/thumb/hm_S828.jpg",
"price": 1500,
"top": true
},
{
"code": "VL312",
"name": "Premiere Largo",
"en": "Staron Premiere 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Premiere",
"hex": "#edeef2",
"img": "swatches/staron/st_VL312.jpg",
"thumb": "swatches/staron/thumb/st_VL312.jpg",
"price": 1500,
"top": true
},
{
"code": "VL322",
"name": "Premiere Legato",
"en": "Staron Premiere 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Premiere",
"hex": "#ccced0",
"img": "swatches/staron/st_VL322.jpg",
"thumb": "swatches/staron/thumb/st_VL322.jpg",
"price": 1500,
"top": true
},
{
"code": "VG392",
"name": "Premiere Gravita",
"en": "Staron Premiere 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Premiere",
"hex": "#202125",
"img": "swatches/staron/st_VG392.jpg",
"thumb": "swatches/staron/thumb/st_VG392.jpg",
"price": 1500,
"top": true
},
{
"code": "VC110",
"name": "Cotton White",
"en": "Staron Supreme 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Supreme",
"hex": "#e9e9eb",
"img": "swatches/staron/st_VC110.jpg",
"thumb": "swatches/staron/thumb/st_VC110.jpg",
"price": 1500,
"top": true
},
{
"code": "VD111",
"name": "Delphi",
"en": "Staron Supreme 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Supreme",
"hex": "#fafaf8",
"img": "swatches/staron/st_VD111.jpg",
"thumb": "swatches/staron/thumb/st_VD111.jpg",
"price": 1500,
"top": true
},
{
"code": "VM114",
"name": "Morning Sky",
"en": "Staron Supreme 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Supreme",
"hex": "#f0eef2",
"img": "swatches/staron/st_VM114.jpg",
"thumb": "swatches/staron/thumb/st_VM114.jpg",
"price": 1500,
"top": true
},
{
"code": "VR184",
"name": "Reno",
"en": "Staron Supreme 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Supreme",
"hex": "#e5e3de",
"img": "swatches/staron/st_VR184.jpg",
"thumb": "swatches/staron/thumb/st_VR184.jpg",
"price": 1500,
"top": true
},
{
"code": "VC118",
"name": "Cloudbank",
"en": "Staron Supreme 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Supreme",
"hex": "#d9d9d8",
"img": "swatches/staron/st_VC118.jpg",
"thumb": "swatches/staron/thumb/st_VC118.jpg",
"price": 1500,
"top": true
},
{
"code": "VB172",
"name": "Beige Granite",
"en": "Staron Supreme 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Supreme",
"hex": "#efebe6",
"img": "swatches/staron/st_VB172.jpg",
"thumb": "swatches/staron/thumb/st_VB172.jpg",
"price": 1500,
"top": true
},
{
"code": "VM143",
"name": "Magnolia",
"en": "Staron Supreme 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Supreme",
"hex": "#f3f1ea",
"img": "swatches/staron/st_VM143.jpg",
"thumb": "swatches/staron/thumb/st_VM143.jpg",
"price": 1500,
"top": true
},
{
"code": "VO171",
"name": "Ocean View",
"en": "Staron Supreme 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Supreme",
"hex": "#eeedea",
"img": "swatches/staron/st_VO171.jpg",
"thumb": "swatches/staron/thumb/st_VO171.jpg",
"price": 1500,
"top": true
},
{
"code": "VN144",
"name": "Natural Bridge",
"en": "Staron Supreme 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Supreme",
"hex": "#dad7cd",
"img": "swatches/staron/st_VN144.jpg",
"thumb": "swatches/staron/thumb/st_VN144.jpg",
"price": 1500,
"top": true
},
{
"code": "VD175",
"name": "Dandelion",
"en": "Staron Supreme 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Supreme",
"hex": "#d0c9b5",
"img": "swatches/staron/st_VD175.jpg",
"thumb": "swatches/staron/thumb/st_VD175.jpg",
"price": 1500,
"top": true
},
{
"code": "VU127",
"name": "Urban Grey",
"en": "Staron Supreme 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Supreme",
"hex": "#aeaeae",
"img": "swatches/staron/st_VU127.jpg",
"thumb": "swatches/staron/thumb/st_VU127.jpg",
"price": 1500,
"top": true
},
{
"code": "VD126",
"name": "Dawn",
"en": "Staron Supreme 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Supreme",
"hex": "#c7c6c1",
"img": "swatches/staron/st_VD126.jpg",
"thumb": "swatches/staron/thumb/st_VD126.jpg",
"price": 1500,
"top": true
},
{
"code": "VL155",
"name": "Loam",
"en": "Staron Supreme 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Supreme",
"hex": "#4a3a2c",
"img": "swatches/staron/st_VL155.jpg",
"thumb": "swatches/staron/thumb/st_VL155.jpg",
"price": 1500,
"top": true
},
{
"code": "VP159",
"name": "Presto",
"en": "Staron Supreme 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Supreme",
"hex": "#2e2e33",
"img": "swatches/staron/st_VP159.jpg",
"thumb": "swatches/staron/thumb/st_VP159.jpg",
"price": 1500,
"top": true
},
{
"code": "NC912",
"name": "Stucco Cotton",
"en": "Staron Stucco 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Stucco",
"hex": "#f4f4f4",
"img": "swatches/staron/st_NC912.jpg",
"thumb": "swatches/staron/thumb/st_NC912.jpg",
"price": 1500,
"top": true
},
{
"code": "NE945",
"name": "Stucco Earth",
"en": "Staron Stucco 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Stucco",
"hex": "#cfccc4",
"img": "swatches/staron/st_NE945.jpg",
"thumb": "swatches/staron/thumb/st_NE945.jpg",
"price": 1500,
"top": true
},
{
"code": "SC444",
"name": "Eclipse Cream",
"en": "Staron Eclipse 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Eclipse",
"hex": "#e8e8dc",
"img": "swatches/staron/st_SC444.jpg",
"thumb": "swatches/staron/thumb/st_SC444.jpg",
"price": 1500,
"top": true
},
{
"code": "SL477",
"name": "Eclipse Luna",
"en": "Staron Eclipse 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Eclipse",
"hex": "#bbbab7",
"img": "swatches/staron/st_SL477.jpg",
"thumb": "swatches/staron/thumb/st_SL477.jpg",
"price": 1500,
"top": true
},
{
"code": "MU010",
"name": "Ultra Bright",
"en": "Staron Functional 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Functional",
"hex": "#ffffff",
"img": "swatches/staron/st_MU010.jpg",
"thumb": "swatches/staron/thumb/st_MU010.jpg",
"price": 1500,
"top": true
},
{
"code": "ML612",
"name": "Evermoin Limpio",
"en": "Staron Functional 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Functional",
"hex": "#f0edee",
"img": "swatches/staron/st_ML612.jpg",
"thumb": "swatches/staron/thumb/st_ML612.jpg",
"price": 1500,
"top": true
},
{
"code": "QS288",
"name": "Quarry Starred",
"en": "Staron Quarry 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Quarry",
"hex": "#4a4947",
"img": "swatches/staron/st_QS288.jpg",
"thumb": "swatches/staron/thumb/st_QS288.jpg",
"price": 1500,
"top": true
},
{
"code": "EY510",
"name": "Metallic Yukon",
"en": "Staron Metallic 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Metallic",
"hex": "#fcfcfa",
"img": "swatches/staron/st_EY510.jpg",
"thumb": "swatches/staron/thumb/st_EY510.jpg",
"price": 1500,
"top": true
},
{
"code": "EG595",
"name": "Metallic Galaxy",
"en": "Staron Metallic 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Metallic",
"hex": "#2b2929",
"img": "swatches/staron/st_EG595.jpg",
"thumb": "swatches/staron/thumb/st_EG595.jpg",
"price": 1500,
"top": true
},
{
"code": "PF812",
"name": "Pebble Frost",
"en": "Staron Pebble 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Pebble",
"hex": "#fbfafb",
"img": "swatches/staron/st_PF812.jpg",
"thumb": "swatches/staron/thumb/st_PF812.jpg",
"price": 1500,
"top": true
},
{
"code": "PS813",
"name": "Pebble Swan",
"en": "Staron Pebble 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Pebble",
"hex": "#f7f7f9",
"img": "swatches/staron/st_PS813.jpg",
"thumb": "swatches/staron/thumb/st_PS813.jpg",
"price": 1500,
"top": true
},
{
"code": "PM832",
"name": "Pebble Moon",
"en": "Staron Pebble 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Pebble",
"hex": "#eeede8",
"img": "swatches/staron/st_PM832.jpg",
"thumb": "swatches/staron/thumb/st_PM832.jpg",
"price": 1500,
"top": true
},
{
"code": "PS820",
"name": "Pebble Saratoga",
"en": "Staron Pebble 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Pebble",
"hex": "#ede8e2",
"img": "swatches/staron/st_PS820.jpg",
"thumb": "swatches/staron/thumb/st_PS820.jpg",
"price": 1500,
"top": true
},
{
"code": "PC842",
"name": "Pebble Chiffon",
"en": "Staron Pebble 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Pebble",
"hex": "#dfdacf",
"img": "swatches/staron/st_PC842.jpg",
"thumb": "swatches/staron/thumb/st_PC842.jpg",
"price": 1500,
"top": true
},
{
"code": "PT845",
"name": "Pebble Tea Rose",
"en": "Staron Pebble 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Pebble",
"hex": "#e5e0d4",
"img": "swatches/staron/st_PT845.jpg",
"thumb": "swatches/staron/thumb/st_PT845.jpg",
"price": 1500,
"top": true
},
{
"code": "PC821",
"name": "Pebble Caper",
"en": "Staron Pebble 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Pebble",
"hex": "#e2dfd9",
"img": "swatches/staron/st_PC821.jpg",
"thumb": "swatches/staron/thumb/st_PC821.jpg",
"price": 1500,
"top": true
},
{
"code": "PG840",
"name": "Pebble Gold",
"en": "Staron Pebble 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Pebble",
"hex": "#e2d4ba",
"img": "swatches/staron/st_PG840.jpg",
"thumb": "swatches/staron/thumb/st_PG840.jpg",
"price": 1500,
"top": true
},
{
"code": "PS854",
"name": "Pebble Spinel",
"en": "Staron Pebble 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Pebble",
"hex": "#c8bba6",
"img": "swatches/staron/st_PS854.jpg",
"thumb": "swatches/staron/thumb/st_PS854.jpg",
"price": 1500,
"top": true
},
{
"code": "PB852",
"name": "Pebble Boulder",
"en": "Staron Pebble 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Pebble",
"hex": "#9d9992",
"img": "swatches/staron/st_PB852.jpg",
"thumb": "swatches/staron/thumb/st_PB852.jpg",
"price": 1500,
"top": true
},
{
"code": "PC855",
"name": "Pebble Chocolate",
"en": "Staron Pebble 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Pebble",
"hex": "#443c33",
"img": "swatches/staron/st_PC855.jpg",
"thumb": "swatches/staron/thumb/st_PC855.jpg",
"price": 1500,
"top": true
},
{
"code": "PE814",
"name": "Pebble Ebony",
"en": "Staron Pebble 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Pebble",
"hex": "#181818",
"img": "swatches/staron/st_PE814.jpg",
"thumb": "swatches/staron/thumb/st_PE814.jpg",
"price": 1500,
"top": true
},
{
"code": "PB870",
"name": "Pebble Blue",
"en": "Staron Pebble 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Pebble",
"hex": "#575d6e",
"img": "swatches/staron/st_PB870.jpg",
"thumb": "swatches/staron/thumb/st_PB870.jpg",
"price": 1500,
"top": true
},
{
"code": "AG612",
"name": "Aspen Glacier",
"en": "Staron Aspen 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Aspen",
"hex": "#f8f8fa",
"img": "swatches/staron/st_AG612.jpg",
"thumb": "swatches/staron/thumb/st_AG612.jpg",
"price": 1500,
"top": true
},
{
"code": "AS610",
"name": "Aspen Snow",
"en": "Staron Aspen 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Aspen",
"hex": "#f5f5f5",
"img": "swatches/staron/st_AS610.jpg",
"thumb": "swatches/staron/thumb/st_AS610.jpg",
"price": 1500,
"top": true
},
{
"code": "AG636",
"name": "Aspen Glow",
"en": "Staron Aspen 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Aspen",
"hex": "#edeae2",
"img": "swatches/staron/st_AG636.jpg",
"thumb": "swatches/staron/thumb/st_AG636.jpg",
"price": 1500,
"top": true
},
{
"code": "AA625",
"name": "Aspen Alder",
"en": "Staron Aspen 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Aspen",
"hex": "#ecebea",
"img": "swatches/staron/st_AA625.jpg",
"thumb": "swatches/staron/thumb/st_AA625.jpg",
"price": 1500,
"top": true
},
{
"code": "AS644",
"name": "Aspen Stucco",
"en": "Staron Aspen 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Aspen",
"hex": "#f5f2e9",
"img": "swatches/staron/st_AS644.jpg",
"thumb": "swatches/staron/thumb/st_AS644.jpg",
"price": 1500,
"top": true
},
{
"code": "AP640",
"name": "Aspen Pepper",
"en": "Staron Aspen 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Aspen",
"hex": "#cfc9c2",
"img": "swatches/staron/st_AP640.jpg",
"thumb": "swatches/staron/thumb/st_AP640.jpg",
"price": 1500,
"top": true
},
{
"code": "AG620",
"name": "Aspen Grey",
"en": "Staron Aspen 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Aspen",
"hex": "#c1bebd",
"img": "swatches/staron/st_AG620.jpg",
"thumb": "swatches/staron/thumb/st_AG620.jpg",
"price": 1500,
"top": true
},
{
"code": "AC629",
"name": "Aspen Concrete",
"en": "Staron Aspen 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Aspen",
"hex": "#94938f",
"img": "swatches/staron/st_AC629.jpg",
"thumb": "swatches/staron/thumb/st_AC629.jpg",
"price": 1500,
"top": true
},
{
"code": "AM633",
"name": "Aspen Mine",
"en": "Staron Aspen 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Aspen",
"hex": "#53453b",
"img": "swatches/staron/st_AM633.jpg",
"thumb": "swatches/staron/thumb/st_AM633.jpg",
"price": 1500,
"top": true
},
{
"code": "SI414",
"name": "Sanded Icicle",
"en": "Staron Sanded 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Sanded",
"hex": "#faf9f9",
"img": "swatches/staron/st_SI414.jpg",
"thumb": "swatches/staron/thumb/st_SI414.jpg",
"price": 1500,
"top": true
},
{
"code": "SM421",
"name": "Sanded Cream",
"en": "Staron Sanded 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Sanded",
"hex": "#f7f7f5",
"img": "swatches/staron/st_SM421.jpg",
"thumb": "swatches/staron/thumb/st_SM421.jpg",
"price": 1500,
"top": true
},
{
"code": "SD413",
"name": "Sanded Dover",
"en": "Staron Sanded 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Sanded",
"hex": "#dbdbdc",
"img": "swatches/staron/st_SD413.jpg",
"thumb": "swatches/staron/thumb/st_SD413.jpg",
"price": 1500,
"top": true
},
{
"code": "SG420",
"name": "Sanded Grey",
"en": "Staron Sanded 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Sanded",
"hex": "#bdbfc1",
"img": "swatches/staron/st_SG420.jpg",
"thumb": "swatches/staron/thumb/st_SG420.jpg",
"price": 1500,
"top": true
},
{
"code": "SS440",
"name": "Sanded Sahara",
"en": "Staron Sanded 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Sanded",
"hex": "#ede4d4",
"img": "swatches/staron/st_SS440.jpg",
"thumb": "swatches/staron/thumb/st_SS440.jpg",
"price": 1500,
"top": true
},
{
"code": "SH428",
"name": "Sanded Heron",
"en": "Staron Sanded 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Sanded",
"hex": "#a4a39e",
"img": "swatches/staron/st_SH428.jpg",
"thumb": "swatches/staron/thumb/st_SH428.jpg",
"price": 1500,
"top": true
},
{
"code": "SC475",
"name": "Sanded Clay",
"en": "Staron Sanded 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Sanded",
"hex": "#7d6f5f",
"img": "swatches/staron/st_SC475.jpg",
"thumb": "swatches/staron/thumb/st_SC475.jpg",
"price": 1500,
"top": true
},
{
"code": "ST486",
"name": "Sanded Taupe",
"en": "Staron Sanded 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Sanded",
"hex": "#6b6861",
"img": "swatches/staron/st_ST486.jpg",
"thumb": "swatches/staron/thumb/st_ST486.jpg",
"price": 1500,
"top": true
},
{
"code": "SC457",
"name": "Sanded Chestnut",
"en": "Staron Sanded 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Sanded",
"hex": "#50463d",
"img": "swatches/staron/st_SC457.jpg",
"thumb": "swatches/staron/thumb/st_SC457.jpg",
"price": 1500,
"top": true
},
{
"code": "SO423",
"name": "Sanded Onyx",
"en": "Staron Sanded 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Sanded",
"hex": "#343331",
"img": "swatches/staron/st_SO423.jpg",
"thumb": "swatches/staron/thumb/st_SO423.jpg",
"price": 1500,
"top": true
},
{
"code": "SQ019",
"name": "Quasar White",
"en": "Staron Solid 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Solid",
"hex": "#ffffff",
"img": "swatches/staron/st_SQ019.jpg",
"thumb": "swatches/staron/thumb/st_SQ019.jpg",
"price": 1500,
"top": true
},
{
"code": "BW010",
"name": "Bright White",
"en": "Staron Solid 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Solid",
"hex": "#fffffd",
"img": "swatches/staron/st_BW010.jpg",
"thumb": "swatches/staron/thumb/st_BW010.jpg",
"price": 1500,
"top": true
},
{
"code": "SD001",
"name": "Dazzling White",
"en": "Staron Solid 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Solid",
"hex": "#fcfcfc",
"img": "swatches/staron/st_SD001.jpg",
"thumb": "swatches/staron/thumb/st_SD001.jpg",
"price": 1500,
"top": true
},
{
"code": "SV041",
"name": "Natural",
"en": "Staron Solid 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Solid",
"hex": "#f9f7ea",
"img": "swatches/staron/st_SV041.jpg",
"thumb": "swatches/staron/thumb/st_SV041.jpg",
"price": 1500,
"top": true
},
{
"code": "ON095",
"name": "Onyx",
"en": "Staron Solid 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Solid",
"hex": "#191919",
"img": "swatches/staron/st_ON095.jpg",
"thumb": "swatches/staron/thumb/st_ON095.jpg",
"price": 1500,
"top": true
},
{
"code": "SO064",
"name": "Oasis",
"en": "Staron Solid 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Solid",
"hex": "#deec5b",
"img": "swatches/staron/st_SO064.jpg",
"thumb": "swatches/staron/thumb/st_SO064.jpg",
"price": 1500,
"top": true
},
{
"code": "SC052",
"name": "California Poppy",
"en": "Staron Solid 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Solid",
"hex": "#fd6011",
"img": "swatches/staron/st_SC052.jpg",
"thumb": "swatches/staron/thumb/st_SC052.jpg",
"price": 1500,
"top": true
},
{
"code": "SU053",
"name": "Univers",
"en": "Staron Solid 系列　人造石（壓克力系）　台灣官網色卡　官網未標價，暫定 1,500 元/才",
"brand": "LOTTE Staron",
"series": "Solid",
"hex": "#940605",
"img": "swatches/staron/st_SU053.jpg",
"thumb": "swatches/staron/thumb/st_SU053.jpg",
"price": 1500,
"top": true
},
{
"code": "CO-TRAVERTINE-ROMA",
"name": "Travertine Roma",
"en": "Corian 石紋／花紋　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　新色　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "石紋／花紋",
"hex": "#d0baa1",
"img": "swatches/corian/co_travertine-roma.jpg",
"thumb": "swatches/corian/thumb/co_travertine-roma.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-TRAVERTINE-FIRENZE",
"name": "Travertine Firenze",
"en": "Corian 石紋／花紋　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　新色　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "石紋／花紋",
"hex": "#e6e0da",
"img": "swatches/corian/co_travertine-firenze.jpg",
"thumb": "swatches/corian/thumb/co_travertine-firenze.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-VASTO-GREIGE",
"name": "Vasto Greige",
"en": "Corian 石紋／花紋　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　新色　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "石紋／花紋",
"hex": "#f7f5f2",
"img": "swatches/corian/co_vasto-greige.jpg",
"thumb": "swatches/corian/thumb/co_vasto-greige.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-VASTO-LAGUNA",
"name": "Vasto Laguna",
"en": "Corian 石紋／花紋　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　新色　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "石紋／花紋",
"hex": "#f5f2ed",
"img": "swatches/corian/co_vasto-laguna.jpg",
"thumb": "swatches/corian/thumb/co_vasto-laguna.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-ARTISTA-DRIFT",
"name": "Artista Drift",
"en": "Corian Artista　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　新色　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "Artista",
"hex": "#fcfbf7",
"img": "swatches/corian/co_artista-drift.jpg",
"thumb": "swatches/corian/thumb/co_artista-drift.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-ARTISTA-MOCHA",
"name": "Artista Mocha",
"en": "Corian Artista　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　新色　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "Artista",
"hex": "#594844",
"img": "swatches/corian/co_artista-mocha.jpg",
"thumb": "swatches/corian/thumb/co_artista-mocha.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-CITY-ROAST",
"name": "City Roast",
"en": "Corian 石紋／花紋　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　新色　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "石紋／花紋",
"hex": "#5b4c49",
"img": "swatches/corian/co_city-roast.jpg",
"thumb": "swatches/corian/thumb/co_city-roast.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-LAVA-DRIFT",
"name": "Lava Drift",
"en": "Corian 石紋／花紋　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "石紋／花紋",
"hex": "#8c8b92",
"img": "swatches/corian/co_lava-drift.jpg",
"thumb": "swatches/corian/thumb/co_lava-drift.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-CREME-ROYALE",
"name": "Crème Royale",
"en": "Corian 石紋／花紋　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "石紋／花紋",
"hex": "#c5c1c2",
"img": "swatches/corian/co_creme-royale.jpg",
"thumb": "swatches/corian/thumb/co_creme-royale.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-RAIN-STREAK",
"name": "Rain Streak",
"en": "Corian 石紋／花紋　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "石紋／花紋",
"hex": "#d6d5d8",
"img": "swatches/corian/co_rain-streak.jpg",
"thumb": "swatches/corian/thumb/co_rain-streak.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-PEBBLE-LANE",
"name": "Pebble Lane",
"en": "Corian 石紋／花紋　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　新色　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "石紋／花紋",
"hex": "#dbcbbc",
"img": "swatches/corian/co_pebble-lane.jpg",
"thumb": "swatches/corian/thumb/co_pebble-lane.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-STONIQUE",
"name": "Stonique",
"en": "Corian 石紋／花紋　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "石紋／花紋",
"hex": "#efedeb",
"img": "swatches/corian/co_stonique.jpg",
"thumb": "swatches/corian/thumb/co_stonique.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-EXCAVAGE",
"name": "Excavage",
"en": "Corian 石紋／花紋　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "石紋／花紋",
"hex": "#d7d2cc",
"img": "swatches/corian/co_excavage.jpg",
"thumb": "swatches/corian/thumb/co_excavage.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-LAGUNA-TERRAZZO",
"name": "Laguna Terrazzo",
"en": "Corian Terrazzo／Aggregate　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "Terrazzo／Aggregate",
"hex": "#dde1e0",
"img": "swatches/corian/co_laguna-terrazzo.jpg",
"thumb": "swatches/corian/thumb/co_laguna-terrazzo.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-PEPPERED-TERRAZZO",
"name": "Peppered Terrazzo",
"en": "Corian Terrazzo／Aggregate　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "Terrazzo／Aggregate",
"hex": "#d1ccc5",
"img": "swatches/corian/co_peppered-terrazzo.jpg",
"thumb": "swatches/corian/thumb/co_peppered-terrazzo.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-STONECREST-SMOKE",
"name": "Stonecrest Smoke",
"en": "Corian 石紋／花紋　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "石紋／花紋",
"hex": "#bdbcbd",
"img": "swatches/corian/co_stonecrest-smoke.jpg",
"thumb": "swatches/corian/thumb/co_stonecrest-smoke.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-CALACATTA-GREIGE",
"name": "Calacatta Greige",
"en": "Corian 石紋／花紋　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "石紋／花紋",
"hex": "#f9f6eb",
"img": "swatches/corian/co_calacatta-greige.jpg",
"thumb": "swatches/corian/thumb/co_calacatta-greige.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-ARTISTA-SAGE",
"name": "Artista Sage",
"en": "Corian Artista　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "Artista",
"hex": "#c3c4be",
"img": "swatches/corian/co_artista-sage.jpg",
"thumb": "swatches/corian/thumb/co_artista-sage.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-ARTISTA-MIST",
"name": "Artista Mist",
"en": "Corian Artista　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "Artista",
"hex": "#9ca4a6",
"img": "swatches/corian/co_artista-mist.jpg",
"thumb": "swatches/corian/thumb/co_artista-mist.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-PROVENCE-NUWOOD",
"name": "Provence Nuwood",
"en": "Corian 素色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　新色　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "素色",
"hex": "#422821",
"img": "swatches/corian/co_provence-nuwood.jpg",
"thumb": "swatches/corian/thumb/co_provence-nuwood.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-CIRRUS-WHITE",
"name": "Cirrus White",
"en": "Corian 素色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "素色",
"hex": "#fcf9f2",
"img": "swatches/corian/co_cirrus-white.jpg",
"thumb": "swatches/corian/thumb/co_cirrus-white.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-DUNE-PRIMA",
"name": "Dune Prima",
"en": "Corian Prima　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "Prima",
"hex": "#e1d9cd",
"img": "swatches/corian/co_dune-prima.jpg",
"thumb": "swatches/corian/thumb/co_dune-prima.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-SAND-STORM",
"name": "Sand Storm",
"en": "Corian 素色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "素色",
"hex": "#ebe6df",
"img": "swatches/corian/co_sand-storm.jpg",
"thumb": "swatches/corian/thumb/co_sand-storm.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-NATURAL-GRAY",
"name": "Natural Gray",
"en": "Corian 素色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "素色",
"hex": "#8e8b8f",
"img": "swatches/corian/co_natural-gray.jpg",
"thumb": "swatches/corian/thumb/co_natural-gray.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-ARTISTA-BEIGE",
"name": "Artista Beige",
"en": "Corian Artista　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "Artista",
"hex": "#aba59d",
"img": "swatches/corian/co_artista-beige.jpg",
"thumb": "swatches/corian/thumb/co_artista-beige.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-ARTISTA-CANVAS",
"name": "Artista Canvas",
"en": "Corian Artista　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "Artista",
"hex": "#dfdad1",
"img": "swatches/corian/co_artista-canvas.jpg",
"thumb": "swatches/corian/thumb/co_artista-canvas.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-ARTISTA-DUST",
"name": "Artista Dust",
"en": "Corian Artista　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "Artista",
"hex": "#908c86",
"img": "swatches/corian/co_artista-dust.jpg",
"thumb": "swatches/corian/thumb/co_artista-dust.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-ARTISTA-GRAY",
"name": "Artista Gray",
"en": "Corian Artista　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "Artista",
"hex": "#c0c1bb",
"img": "swatches/corian/co_artista-gray.jpg",
"thumb": "swatches/corian/thumb/co_artista-gray.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-CARRARA-CREMA",
"name": "Carrara Crema",
"en": "Corian 石紋／花紋　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "石紋／花紋",
"hex": "#e1dacf",
"img": "swatches/corian/co_carrara-crema.jpg",
"thumb": "swatches/corian/thumb/co_carrara-crema.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-CARRARA-LINO",
"name": "Carrara Lino",
"en": "Corian 石紋／花紋　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "石紋／花紋",
"hex": "#ddddd9",
"img": "swatches/corian/co_carrara-lino.jpg",
"thumb": "swatches/corian/thumb/co_carrara-lino.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-SPARKLING-GRANITA",
"name": "Sparkling Granita",
"en": "Corian Terrazzo／Aggregate　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "Terrazzo／Aggregate",
"hex": "#f3f3f2",
"img": "swatches/corian/co_sparkling-granita.jpg",
"thumb": "swatches/corian/thumb/co_sparkling-granita.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-NEUTRAL-AGGREGATE",
"name": "Neutral Aggregate",
"en": "Corian Terrazzo／Aggregate　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "Terrazzo／Aggregate",
"hex": "#b8afa4",
"img": "swatches/corian/co_neutral-aggregate.jpg",
"thumb": "swatches/corian/thumb/co_neutral-aggregate.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-ASH-AGGREGATE",
"name": "Ash Aggregate",
"en": "Corian Terrazzo／Aggregate　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "Terrazzo／Aggregate",
"hex": "#847f77",
"img": "swatches/corian/co_ash-aggregate.jpg",
"thumb": "swatches/corian/thumb/co_ash-aggregate.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-WEATHERED-AGGREGAT",
"name": "Weathered Aggregate",
"en": "Corian Terrazzo／Aggregate　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "Terrazzo／Aggregate",
"hex": "#7a7168",
"img": "swatches/corian/co_weathered-aggregate.jpg",
"thumb": "swatches/corian/thumb/co_weathered-aggregate.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-VERDANT",
"name": "Verdant",
"en": "Corian 素色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "素色",
"hex": "#5e7472",
"img": "swatches/corian/co_verdant.jpg",
"thumb": "swatches/corian/thumb/co_verdant.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-LAGUNA",
"name": "Laguna",
"en": "Corian 石紋／花紋　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "石紋／花紋",
"hex": "#052d51",
"img": "swatches/corian/co_laguna.jpg",
"thumb": "swatches/corian/thumb/co_laguna.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-DOMINO-TERRAZZO",
"name": "Domino Terrazzo",
"en": "Corian Terrazzo／Aggregate　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "Terrazzo／Aggregate",
"hex": "#d4d6d3",
"img": "swatches/corian/co_domino-terrazzo.jpg",
"thumb": "swatches/corian/thumb/co_domino-terrazzo.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-CARBON-AGGREGATE",
"name": "Carbon Aggregate",
"en": "Corian Terrazzo／Aggregate　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "Terrazzo／Aggregate",
"hex": "#515251",
"img": "swatches/corian/co_carbon-aggregate.jpg",
"thumb": "swatches/corian/thumb/co_carbon-aggregate.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-VENARO-WHITE",
"name": "Venaro White",
"en": "Corian 石紋／花紋　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "石紋／花紋",
"hex": "#f9f6f0",
"img": "swatches/corian/co_venaro-white.jpg",
"thumb": "swatches/corian/thumb/co_venaro-white.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-ARCTIC-ICE",
"name": "Arctic Ice",
"en": "Corian 素色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "素色",
"hex": "#f9f7ea",
"img": "swatches/corian/co_arctic-ice.jpg",
"thumb": "swatches/corian/thumb/co_arctic-ice.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-GLACIER-WHITE",
"name": "Glacier White",
"en": "Corian 素色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "素色",
"hex": "#f3efee",
"img": "swatches/corian/co_glacier-white.jpg",
"thumb": "swatches/corian/thumb/co_glacier-white.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-DESIGNER-WHITE",
"name": "Designer White",
"en": "Corian 素色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "素色",
"hex": "#ffffff",
"img": "swatches/corian/co_designer-white.jpg",
"thumb": "swatches/corian/thumb/co_designer-white.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-CAMEO-WHITE",
"name": "Cameo White",
"en": "Corian 素色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "素色",
"hex": "#f3f0e5",
"img": "swatches/corian/co_cameo-white.jpg",
"thumb": "swatches/corian/thumb/co_cameo-white.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-EVEREST",
"name": "Everest",
"en": "Corian 素色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "素色",
"hex": "#f3f2ed",
"img": "swatches/corian/co_everest.jpg",
"thumb": "swatches/corian/thumb/co_everest.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-WHITE-JASMINE",
"name": "White Jasmine",
"en": "Corian 素色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "素色",
"hex": "#fdfcf1",
"img": "swatches/corian/co_white-jasmine.jpg",
"thumb": "swatches/corian/thumb/co_white-jasmine.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-ARROWROOT",
"name": "Arrowroot",
"en": "Corian 素色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "素色",
"hex": "#e1e0db",
"img": "swatches/corian/co_arrowroot.jpg",
"thumb": "swatches/corian/thumb/co_arrowroot.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-ELEGANT-GRAY",
"name": "Elegant Gray",
"en": "Corian 素色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "素色",
"hex": "#beb5a3",
"img": "swatches/corian/co_elegant-gray.jpg",
"thumb": "swatches/corian/thumb/co_elegant-gray.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-BISQUE",
"name": "Bisque",
"en": "Corian 素色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "素色",
"hex": "#ede6d4",
"img": "swatches/corian/co_bisque.jpg",
"thumb": "swatches/corian/thumb/co_bisque.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-BONE",
"name": "Bone",
"en": "Corian 素色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "素色",
"hex": "#dad3b9",
"img": "swatches/corian/co_bone.jpg",
"thumb": "swatches/corian/thumb/co_bone.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-SAGEBRUSH",
"name": "Sagebrush",
"en": "Corian 素色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "素色",
"hex": "#ada592",
"img": "swatches/corian/co_sagebrush.jpg",
"thumb": "swatches/corian/thumb/co_sagebrush.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-SANDALWOOD",
"name": "Sandalwood",
"en": "Corian 素色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "素色",
"hex": "#bdaea0",
"img": "swatches/corian/co_sandalwood.jpg",
"thumb": "swatches/corian/thumb/co_sandalwood.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-SILVER-BIRCH",
"name": "Silver Birch",
"en": "Corian 素色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "素色",
"hex": "#e4e0dd",
"img": "swatches/corian/co_silver-birch.jpg",
"thumb": "swatches/corian/thumb/co_silver-birch.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-ABALONE",
"name": "Abalone",
"en": "Corian 素色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "素色",
"hex": "#f5edda",
"img": "swatches/corian/co_abalone.jpg",
"thumb": "swatches/corian/thumb/co_abalone.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-LINEN",
"name": "Linen",
"en": "Corian 素色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "素色",
"hex": "#ece5db",
"img": "swatches/corian/co_linen.jpg",
"thumb": "swatches/corian/thumb/co_linen.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-CLAM-SHELL",
"name": "Clam Shell",
"en": "Corian 素色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "素色",
"hex": "#d9d1c3",
"img": "swatches/corian/co_clam-shell.jpg",
"thumb": "swatches/corian/thumb/co_clam-shell.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-SAVANNAH",
"name": "Savannah",
"en": "Corian 素色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "素色",
"hex": "#e4dccd",
"img": "swatches/corian/co_savannah.jpg",
"thumb": "swatches/corian/thumb/co_savannah.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-SAHARA",
"name": "Sahara",
"en": "Corian 素色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "素色",
"hex": "#dbd0ba",
"img": "swatches/corian/co_sahara.jpg",
"thumb": "swatches/corian/thumb/co_sahara.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-HOT",
"name": "Hot",
"en": "Corian 素色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "素色",
"hex": "#903233",
"img": "swatches/corian/co_hot.jpg",
"thumb": "swatches/corian/thumb/co_hot.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-AURORA",
"name": "Aurora",
"en": "Corian 素色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "素色",
"hex": "#d6c9b4",
"img": "swatches/corian/co_aurora.jpg",
"thumb": "swatches/corian/thumb/co_aurora.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-WITCH-HAZEL",
"name": "Witch Hazel",
"en": "Corian 素色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "素色",
"hex": "#e3dacc",
"img": "swatches/corian/co_witch-hazel.jpg",
"thumb": "swatches/corian/thumb/co_witch-hazel.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-JUNIPER",
"name": "Juniper",
"en": "Corian 素色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "素色",
"hex": "#8e8c8e",
"img": "swatches/corian/co_juniper.jpg",
"thumb": "swatches/corian/thumb/co_juniper.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-PEARL-GRAY",
"name": "Pearl Gray",
"en": "Corian 素色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "素色",
"hex": "#c7c4bd",
"img": "swatches/corian/co_pearl-gray.jpg",
"thumb": "swatches/corian/thumb/co_pearl-gray.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-RAIN-CLOUD",
"name": "Rain Cloud",
"en": "Corian 素色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "素色",
"hex": "#dcd9d6",
"img": "swatches/corian/co_rain-cloud.jpg",
"thumb": "swatches/corian/thumb/co_rain-cloud.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-SILVER-GRAY",
"name": "Silver Gray",
"en": "Corian 素色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "素色",
"hex": "#afaeac",
"img": "swatches/corian/co_silver-gray.jpg",
"thumb": "swatches/corian/thumb/co_silver-gray.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-DOVE",
"name": "Dove",
"en": "Corian 素色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "素色",
"hex": "#a19c98",
"img": "swatches/corian/co_dove.jpg",
"thumb": "swatches/corian/thumb/co_dove.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-ROSEMARY",
"name": "Rosemary",
"en": "Corian 素色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "素色",
"hex": "#79715c",
"img": "swatches/corian/co_rosemary.jpg",
"thumb": "swatches/corian/thumb/co_rosemary.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-SORREL",
"name": "Sorrel",
"en": "Corian 素色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "素色",
"hex": "#4c4741",
"img": "swatches/corian/co_sorrel.jpg",
"thumb": "swatches/corian/thumb/co_sorrel.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-PLATINUM",
"name": "Platinum",
"en": "Corian 素色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "素色",
"hex": "#918f8e",
"img": "swatches/corian/co_platinum.jpg",
"thumb": "swatches/corian/thumb/co_platinum.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-LAVA-ROCK",
"name": "Lava Rock",
"en": "Corian 石紋／花紋　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "石紋／花紋",
"hex": "#535250",
"img": "swatches/corian/co_lava-rock.jpg",
"thumb": "swatches/corian/thumb/co_lava-rock.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-DEEP-CLOUD",
"name": "Deep Cloud",
"en": "Corian DeepColour 深色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "DeepColour 深色",
"hex": "#626260",
"img": "swatches/corian/co_deep-cloud.jpg",
"thumb": "swatches/corian/thumb/co_deep-cloud.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-DEEP-MINK",
"name": "Deep Mink",
"en": "Corian DeepColour 深色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "DeepColour 深色",
"hex": "#4b4640",
"img": "swatches/corian/co_deep-mink.jpg",
"thumb": "swatches/corian/thumb/co_deep-mink.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-DEEP-SABLE",
"name": "Deep Sable",
"en": "Corian DeepColour 深色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "DeepColour 深色",
"hex": "#5f5755",
"img": "swatches/corian/co_deep-sable.jpg",
"thumb": "swatches/corian/thumb/co_deep-sable.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-DEEP-ESPRESSO",
"name": "Deep Espresso",
"en": "Corian DeepColour 深色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "DeepColour 深色",
"hex": "#3d3938",
"img": "swatches/corian/co_deep-espresso.jpg",
"thumb": "swatches/corian/thumb/co_deep-espresso.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-DEEP-STORM",
"name": "Deep Storm",
"en": "Corian DeepColour 深色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "DeepColour 深色",
"hex": "#1c1613",
"img": "swatches/corian/co_deep-storm.jpg",
"thumb": "swatches/corian/thumb/co_deep-storm.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-DEEP-NIGHT-SKY",
"name": "Deep Night Sky",
"en": "Corian DeepColour 深色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "DeepColour 深色",
"hex": "#0d0d0d",
"img": "swatches/corian/co_deep-night-sky.jpg",
"thumb": "swatches/corian/thumb/co_deep-night-sky.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-DEEP-TITANIUM",
"name": "Deep Titanium",
"en": "Corian DeepColour 深色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "DeepColour 深色",
"hex": "#393939",
"img": "swatches/corian/co_deep-titanium.jpg",
"thumb": "swatches/corian/thumb/co_deep-titanium.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-DEEP-BLACK-QUARTZ",
"name": "Deep Black Quartz",
"en": "Corian DeepColour 深色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "DeepColour 深色",
"hex": "#0d0e10",
"img": "swatches/corian/co_deep-black-quartz.jpg",
"thumb": "swatches/corian/thumb/co_deep-black-quartz.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-DEEP-ANTHRACITE",
"name": "Deep Anthracite",
"en": "Corian DeepColour 深色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "DeepColour 深色",
"hex": "#090a0d",
"img": "swatches/corian/co_deep-anthracite.jpg",
"thumb": "swatches/corian/thumb/co_deep-anthracite.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-DEEP-NOCTURNE",
"name": "Deep Nocturne",
"en": "Corian DeepColour 深色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "DeepColour 深色",
"hex": "#000000",
"img": "swatches/corian/co_deep-nocturne.jpg",
"thumb": "swatches/corian/thumb/co_deep-nocturne.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-MODERN-WHITE",
"name": "Modern White",
"en": "Corian 素色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "素色",
"hex": "#fffef9",
"img": "swatches/corian/co_modern-white.jpg",
"thumb": "swatches/corian/thumb/co_modern-white.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-ASH-CONCRETE",
"name": "Ash Concrete",
"en": "Corian Concrete 水泥　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "Concrete 水泥",
"hex": "#908985",
"img": "swatches/corian/co_ash-concrete.jpg",
"thumb": "swatches/corian/thumb/co_ash-concrete.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-NEUTRAL-CONCRETE",
"name": "Neutral Concrete",
"en": "Corian Concrete 水泥　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "Concrete 水泥",
"hex": "#c1bab0",
"img": "swatches/corian/co_neutral-concrete.jpg",
"thumb": "swatches/corian/thumb/co_neutral-concrete.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-NIMBUS-PRIMA",
"name": "Nimbus Prima",
"en": "Corian Prima　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "Prima",
"hex": "#e8e2d2",
"img": "swatches/corian/co_nimbus-prima.jpg",
"thumb": "swatches/corian/thumb/co_nimbus-prima.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-CANVAS",
"name": "Canvas",
"en": "Corian 素色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "素色",
"hex": "#c2baa7",
"img": "swatches/corian/co_canvas.jpg",
"thumb": "swatches/corian/thumb/co_canvas.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-CARBON-CONCRETE",
"name": "Carbon Concrete",
"en": "Corian Concrete 水泥　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "Concrete 水泥",
"hex": "#504f4d",
"img": "swatches/corian/co_carbon-concrete.jpg",
"thumb": "swatches/corian/thumb/co_carbon-concrete.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-RICE-PAPER",
"name": "Rice Paper",
"en": "Corian 素色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "素色",
"hex": "#f8f0e4",
"img": "swatches/corian/co_rice-paper.jpg",
"thumb": "swatches/corian/thumb/co_rice-paper.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-CONCRETE",
"name": "Concrete",
"en": "Corian Concrete 水泥　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "Concrete 水泥",
"hex": "#9a9286",
"img": "swatches/corian/co_concrete.jpg",
"thumb": "swatches/corian/thumb/co_concrete.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-COSMOS-PRIMA",
"name": "Cosmos Prima",
"en": "Corian Prima　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "Prima",
"hex": "#3b3b3b",
"img": "swatches/corian/co_cosmos-prima.jpg",
"thumb": "swatches/corian/thumb/co_cosmos-prima.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-DOESKIN",
"name": "Doeskin",
"en": "Corian 素色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "素色",
"hex": "#7d7167",
"img": "swatches/corian/co_doeskin.jpg",
"thumb": "swatches/corian/thumb/co_doeskin.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-SMOKE-DRIFT-PRIMA",
"name": "Smoke Drift Prima",
"en": "Corian Prima　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "Prima",
"hex": "#b3a89e",
"img": "swatches/corian/co_smoke-drift-prima.jpg",
"thumb": "swatches/corian/thumb/co_smoke-drift-prima.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-SPARKLING-WHITE",
"name": "Sparkling White",
"en": "Corian 素色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "素色",
"hex": "#fffffb",
"img": "swatches/corian/co_sparkling-white.jpg",
"thumb": "swatches/corian/thumb/co_sparkling-white.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-EVENING-PRIMA",
"name": "Evening Prima",
"en": "Corian Prima　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "Prima",
"hex": "#4b4f5a",
"img": "swatches/corian/co_evening-prima.jpg",
"thumb": "swatches/corian/thumb/co_evening-prima.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-WEATHERED-CONCRETE",
"name": "Weathered Concrete",
"en": "Corian Concrete 水泥　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "Concrete 水泥",
"hex": "#7e776f",
"img": "swatches/corian/co_weathered-concrete.jpg",
"thumb": "swatches/corian/thumb/co_weathered-concrete.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-WHIPPED-CREAM",
"name": "Whipped Cream",
"en": "Corian 素色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "素色",
"hex": "#e0dbd0",
"img": "swatches/corian/co_whipped-cream.jpg",
"thumb": "swatches/corian/thumb/co_whipped-cream.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-WHISPER",
"name": "Whisper",
"en": "Corian 素色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "素色",
"hex": "#cfc3b3",
"img": "swatches/corian/co_whisper.jpg",
"thumb": "swatches/corian/thumb/co_whisper.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-GRAY-ONYX",
"name": "Gray Onyx",
"en": "Corian 石紋／花紋　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "石紋／花紋",
"hex": "#e3e3e3",
"img": "swatches/corian/co_gray-onyx.jpg",
"thumb": "swatches/corian/thumb/co_gray-onyx.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-WHITE-ONYX",
"name": "White Onyx",
"en": "Corian 石紋／花紋　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "石紋／花紋",
"hex": "#faf6ee",
"img": "swatches/corian/co_white-onyx.jpg",
"thumb": "swatches/corian/thumb/co_white-onyx.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-WILLOW",
"name": "Willow",
"en": "Corian 素色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "素色",
"hex": "#aeaa9f",
"img": "swatches/corian/co_willow.jpg",
"thumb": "swatches/corian/thumb/co_willow.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-WINDSWEPT-PRIMA",
"name": "Windswept Prima",
"en": "Corian Prima　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "Prima",
"hex": "#b3a492",
"img": "swatches/corian/co_windswept-prima.jpg",
"thumb": "swatches/corian/thumb/co_windswept-prima.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-LIMESTONE-PRIMA",
"name": "Limestone Prima",
"en": "Corian Prima　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "Prima",
"hex": "#e3dfdd",
"img": "swatches/corian/co_limestone-prima.jpg",
"thumb": "swatches/corian/thumb/co_limestone-prima.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-GLACIER-ICE",
"name": "Glacier Ice",
"en": "Corian 素色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "素色",
"hex": "#f3f0e9",
"img": "swatches/corian/co_glacier-ice.jpg",
"thumb": "swatches/corian/thumb/co_glacier-ice.jpg",
"price": 2000,
"top": true
},
{
"code": "CO-ANTARCTICA",
"name": "Antarctica",
"en": "Corian 素色　人造石（壓克力系）　杜邦色卡工具（北美區色號，台灣供應請洽連程實業）　官網未標價，暫定 2,000 元/才",
"brand": "杜邦可麗耐 Corian",
"series": "素色",
"hex": "#f9f8f2",
"img": "swatches/corian/co_antarctica.jpg",
"thumb": "swatches/corian/thumb/co_antarctica.jpg",
"price": 2000,
"top": true
}
]);
