/* 禾邁系統家具 板材花色（來源 hemai.tw/panel_patterns，2026/10 下載；640x400 貼圖在 swatches/hemai/、160x100 縮圖在 thumb/，由 tools 以外的一次性腳本產生）
   色號與伸保或型錄規格色重複者加「禾邁-」前綴；單價先定 130 元/才 */
window.SWATCHES = (window.SWATCHES || []).concat([
{
"code": "K2878",
"name": "雅緻金布紋",
"en": "原廠型號 K2878GT",
"brand": "禾邁",
"series": "KAINDL",
"hex": "#ab9b8e",
"img": "swatches/hemai/hm_K2878.jpg",
"thumb": "swatches/hemai/thumb/hm_K2878.jpg",
"price": 130
},
{
"code": "799",
"name": "艾奇莫鉑金",
"en": "",
"brand": "禾邁",
"series": "Mauro Saviola",
"hex": "#b8b3a7",
"img": "swatches/hemai/hm_799.jpg",
"thumb": "swatches/hemai/thumb/hm_799.jpg",
"price": 130
},
{
"code": "K2828",
"name": "柔光梣木",
"en": "原廠型號 K2828AT",
"brand": "禾邁",
"series": "KAINDL",
"hex": "#dabfa1",
"img": "swatches/hemai/hm_K2828.jpg",
"thumb": "swatches/hemai/thumb/hm_K2828.jpg",
"price": 130
},
{
"code": "K2811",
"name": "天空藍",
"en": "原廠型號 22811MN",
"brand": "禾邁",
"series": "KAINDL",
"hex": "#b0b7bf",
"img": "swatches/hemai/hm_K2811.jpg",
"thumb": "swatches/hemai/thumb/hm_K2811.jpg",
"price": 130
},
{
"code": "798",
"name": "艾奇莫青銅",
"en": "",
"brand": "禾邁",
"series": "Mauro Saviola",
"hex": "#5d544b",
"img": "swatches/hemai/hm_798.jpg",
"thumb": "swatches/hemai/thumb/hm_798.jpg",
"price": 130
},
{
"code": "424",
"name": "坦博拉石紋",
"en": "",
"brand": "禾邁",
"series": "KAINDL",
"hex": "#d3d8d0",
"img": "swatches/hemai/hm_424.jpg",
"thumb": "swatches/hemai/thumb/hm_424.jpg",
"price": 130
},
{
"code": "K2752",
"name": "弗納爾橡木",
"en": "",
"brand": "禾邁",
"series": "KAINDL",
"hex": "#ad8a68",
"img": "swatches/hemai/hm_K2752.jpg",
"thumb": "swatches/hemai/thumb/hm_K2752.jpg",
"price": 130
},
{
"code": "K2753",
"name": "香脂橡木",
"en": "",
"brand": "禾邁",
"series": "KAINDL",
"hex": "#725a43",
"img": "swatches/hemai/hm_K2753.jpg",
"thumb": "swatches/hemai/thumb/hm_K2753.jpg",
"price": 130
},
{
"code": "8801",
"name": "庫金橡木",
"en": "",
"brand": "禾邁",
"series": "實木皮門板",
"hex": "#c3a283",
"img": "swatches/hemai/hm_8801.jpg",
"thumb": "swatches/hemai/thumb/hm_8801.jpg",
"price": 130
},
{
"code": "8802",
"name": "煙色胡桃",
"en": "",
"brand": "禾邁",
"series": "實木皮門板",
"hex": "#604837",
"img": "swatches/hemai/hm_8802.jpg",
"thumb": "swatches/hemai/thumb/hm_8802.jpg",
"price": 130
},
{
"code": "8803",
"name": "茶青橡木",
"en": "",
"brand": "禾邁",
"series": "實木皮門板",
"hex": "#2a2722",
"img": "swatches/hemai/hm_8803.jpg",
"thumb": "swatches/hemai/thumb/hm_8803.jpg",
"price": 130
},
{
"code": "8805",
"name": "霞光胡桃",
"en": "",
"brand": "禾邁",
"series": "實木皮門板",
"hex": "#554234",
"img": "swatches/hemai/hm_8805.jpg",
"thumb": "swatches/hemai/thumb/hm_8805.jpg",
"price": 130
},
{
"code": "8806",
"name": "流金榆木",
"en": "",
"brand": "禾邁",
"series": "實木皮門板",
"hex": "#7b624e",
"img": "swatches/hemai/hm_8806.jpg",
"thumb": "swatches/hemai/thumb/hm_8806.jpg",
"price": 130
},
{
"code": "B073",
"name": "雪伍德極致白木紋",
"en": "",
"brand": "禾邁",
"series": "CLEAF",
"hex": "#c7c3c0",
"img": "swatches/hemai/hm_B073.jpg",
"thumb": "swatches/hemai/thumb/hm_B073.jpg",
"price": 130
},
{
"code": "D026",
"name": "夢塔娜法式香榭織紋",
"en": "",
"brand": "禾邁",
"series": "CLEAF",
"hex": "#9f948f",
"img": "swatches/hemai/hm_D026.jpg",
"thumb": "swatches/hemai/thumb/hm_D026.jpg",
"price": 130
},
{
"code": "FA90",
"name": "勒凡特棕布紋",
"en": "",
"brand": "禾邁",
"series": "CLEAF",
"hex": "#7b726a",
"img": "swatches/hemai/hm_FA90.jpg",
"thumb": "swatches/hemai/thumb/hm_FA90.jpg",
"price": 130
},
{
"code": "FA91",
"name": "柯特夏深棕布紋",
"en": "",
"brand": "禾邁",
"series": "CLEAF",
"hex": "#5d5a55",
"img": "swatches/hemai/hm_FA91.jpg",
"thumb": "swatches/hemai/thumb/hm_FA91.jpg",
"price": 130
},
{
"code": "FB35",
"name": "金屬灰格紋",
"en": "",
"brand": "禾邁",
"series": "CLEAF",
"hex": "#54534f",
"img": "swatches/hemai/hm_FB35.jpg",
"thumb": "swatches/hemai/thumb/hm_FB35.jpg",
"price": 130
},
{
"code": "FB48",
"name": "歐若咖啡金屬石紋",
"en": "",
"brand": "禾邁",
"series": "CLEAF",
"hex": "#3e3932",
"img": "swatches/hemai/hm_FB48.jpg",
"thumb": "swatches/hemai/thumb/hm_FB48.jpg",
"price": 130
},
{
"code": "FB79",
"name": "馬爾羅斯石板白直紋",
"en": "",
"brand": "禾邁",
"series": "CLEAF",
"hex": "#d7d5d3",
"img": "swatches/hemai/hm_FB79.jpg",
"thumb": "swatches/hemai/thumb/hm_FB79.jpg",
"price": 130
},
{
"code": "FB80",
"name": "瑞尼歐香檳金屬",
"en": "",
"brand": "禾邁",
"series": "CLEAF",
"hex": "#968a80",
"img": "swatches/hemai/hm_FB80.jpg",
"thumb": "swatches/hemai/thumb/hm_FB80.jpg",
"price": 130
},
{
"code": "FB81",
"name": "艾瑞迪歐銀白金屬",
"en": "",
"brand": "禾邁",
"series": "CLEAF",
"hex": "#938f83",
"img": "swatches/hemai/hm_FB81.jpg",
"thumb": "swatches/hemai/thumb/hm_FB81.jpg",
"price": 130
},
{
"code": "FB82",
"name": "特盧瑞歐深灰金屬",
"en": "",
"brand": "禾邁",
"series": "CLEAF",
"hex": "#5b5551",
"img": "swatches/hemai/hm_FB82.jpg",
"thumb": "swatches/hemai/thumb/hm_FB82.jpg",
"price": 130
},
{
"code": "FB86",
"name": "克瑞歐深棕金屬",
"en": "",
"brand": "禾邁",
"series": "CLEAF",
"hex": "#372e24",
"img": "swatches/hemai/hm_FB86.jpg",
"thumb": "swatches/hemai/thumb/hm_FB86.jpg",
"price": 130
},
{
"code": "FC14",
"name": "史戈帕深灰岩板",
"en": "",
"brand": "禾邁",
"series": "CLEAF",
"hex": "#474642",
"img": "swatches/hemai/hm_FC14.jpg",
"thumb": "swatches/hemai/thumb/hm_FC14.jpg",
"price": 130
},
{
"code": "FC36",
"name": "彌德納米灰石紋",
"en": "",
"brand": "禾邁",
"series": "CLEAF",
"hex": "#c5b9b0",
"img": "swatches/hemai/hm_FC36.jpg",
"thumb": "swatches/hemai/thumb/hm_FC36.jpg",
"price": 130
},
{
"code": "FC69",
"name": "福勒曼托水磨石",
"en": "",
"brand": "禾邁",
"series": "CLEAF",
"hex": "#959396",
"img": "swatches/hemai/hm_FC69.jpg",
"thumb": "swatches/hemai/thumb/hm_FC69.jpg",
"price": 130
},
{
"code": "FC92",
"name": "邁克瑞歐鑄銀幾何紋",
"en": "",
"brand": "禾邁",
"series": "CLEAF",
"hex": "#201e1c",
"img": "swatches/hemai/hm_FC92.jpg",
"thumb": "swatches/hemai/thumb/hm_FC92.jpg",
"price": 130
},
{
"code": "FC99",
"name": "柯博瑟西那黑石板",
"en": "",
"brand": "禾邁",
"series": "CLEAF",
"hex": "#19191a",
"img": "swatches/hemai/hm_FC99.jpg",
"thumb": "swatches/hemai/thumb/hm_FC99.jpg",
"price": 130
},
{
"code": "FD05",
"name": "布雷托綠繡布紋",
"en": "",
"brand": "禾邁",
"series": "CLEAF",
"hex": "#989594",
"img": "swatches/hemai/hm_FD05.jpg",
"thumb": "swatches/hemai/thumb/hm_FD05.jpg",
"price": 130
},
{
"code": "FD10",
"name": "義式特蘭塔米灰石紋",
"en": "",
"brand": "禾邁",
"series": "CLEAF",
"hex": "#c7c1a8",
"img": "swatches/hemai/hm_FD10.jpg",
"thumb": "swatches/hemai/thumb/hm_FD10.jpg",
"price": 130
},
{
"code": "FD16",
"name": "義式特蘭塔岩灰石紋",
"en": "",
"brand": "禾邁",
"series": "CLEAF",
"hex": "#8d8a7a",
"img": "swatches/hemai/hm_FD16.jpg",
"thumb": "swatches/hemai/thumb/hm_FD16.jpg",
"price": 130
},
{
"code": "FD31",
"name": "阿爾帕卡棉麻米灰布紋",
"en": "",
"brand": "禾邁",
"series": "CLEAF",
"hex": "#a59f89",
"img": "swatches/hemai/hm_FD31.jpg",
"thumb": "swatches/hemai/thumb/hm_FD31.jpg",
"price": 130
},
{
"code": "LN01",
"name": "歐德肯消光深灰自然木紋",
"en": "",
"brand": "禾邁",
"series": "CLEAF",
"hex": "#80756d",
"img": "swatches/hemai/hm_LN01.jpg",
"thumb": "swatches/hemai/thumb/hm_LN01.jpg",
"price": 130
},
{
"code": "LN02",
"name": "歐德肯消光自然木紋",
"en": "",
"brand": "禾邁",
"series": "CLEAF",
"hex": "#af9d91",
"img": "swatches/hemai/hm_LN02.jpg",
"thumb": "swatches/hemai/thumb/hm_LN02.jpg",
"price": 130
},
{
"code": "LR18",
"name": "柴珀灰棕煙燻橡木",
"en": "",
"brand": "禾邁",
"series": "CLEAF",
"hex": "#91857b",
"img": "swatches/hemai/hm_LR18.jpg",
"thumb": "swatches/hemai/thumb/hm_LR18.jpg",
"price": 130
},
{
"code": "LS47",
"name": "波羅諾斯自然胡桃木",
"en": "",
"brand": "禾邁",
"series": "CLEAF",
"hex": "#6c4d32",
"img": "swatches/hemai/hm_LS47.jpg",
"thumb": "swatches/hemai/thumb/hm_LS47.jpg",
"price": 130
},
{
"code": "LS53",
"name": "波羅諾斯深棕胡桃木",
"en": "",
"brand": "禾邁",
"series": "CLEAF",
"hex": "#423323",
"img": "swatches/hemai/hm_LS53.jpg",
"thumb": "swatches/hemai/thumb/hm_LS53.jpg",
"price": 130
},
{
"code": "LS54",
"name": "波羅諾斯淺棕胡桃木",
"en": "",
"brand": "禾邁",
"series": "CLEAF",
"hex": "#63503e",
"img": "swatches/hemai/hm_LS54.jpg",
"thumb": "swatches/hemai/thumb/hm_LS54.jpg",
"price": 130
},
{
"code": "S083",
"name": "那格都淺原木紋",
"en": "",
"brand": "禾邁",
"series": "CLEAF",
"hex": "#d5c0a3",
"img": "swatches/hemai/hm_S083.jpg",
"thumb": "swatches/hemai/thumb/hm_S083.jpg",
"price": 130
},
{
"code": "S158",
"name": "明納托深棕木紋",
"en": "",
"brand": "禾邁",
"series": "CLEAF",
"hex": "#413931",
"img": "swatches/hemai/hm_S158.jpg",
"thumb": "swatches/hemai/thumb/hm_S158.jpg",
"price": 130
},
{
"code": "S191",
"name": "諾希瑪淺棕幾何木紋",
"en": "",
"brand": "禾邁",
"series": "CLEAF",
"hex": "#b59a7a",
"img": "swatches/hemai/hm_S191.jpg",
"thumb": "swatches/hemai/thumb/hm_S191.jpg",
"price": 130
},
{
"code": "S192",
"name": "塔希瑪深棕幾何木紋",
"en": "",
"brand": "禾邁",
"series": "CLEAF",
"hex": "#523f30",
"img": "swatches/hemai/hm_S192.jpg",
"thumb": "swatches/hemai/thumb/hm_S192.jpg",
"price": 130
},
{
"code": "SYM101",
"name": "密涅瓦湖水綠",
"en": "",
"brand": "禾邁",
"series": "SYNCRON 門板",
"hex": "#a6afaa",
"img": "swatches/hemai/hm_SYM101.jpg",
"thumb": "swatches/hemai/thumb/hm_SYM101.jpg",
"price": 130
},
{
"code": "SYM103",
"name": "密涅瓦壁畫藍",
"en": "",
"brand": "禾邁",
"series": "SYNCRON 門板",
"hex": "#acbabc",
"img": "swatches/hemai/hm_SYM103.jpg",
"thumb": "swatches/hemai/thumb/hm_SYM103.jpg",
"price": 130
},
{
"code": "SYM105",
"name": "密涅瓦火山灰",
"en": "",
"brand": "禾邁",
"series": "SYNCRON 門板",
"hex": "#aaa6a1",
"img": "swatches/hemai/hm_SYM105.jpg",
"thumb": "swatches/hemai/thumb/hm_SYM105.jpg",
"price": 130
},
{
"code": "SYM107",
"name": "密涅瓦檸檬黃",
"en": "",
"brand": "禾邁",
"series": "SYNCRON 門板",
"hex": "#c7c3b5",
"img": "swatches/hemai/hm_SYM107.jpg",
"thumb": "swatches/hemai/thumb/hm_SYM107.jpg",
"price": 130
},
{
"code": "SYM109",
"name": "密涅瓦緞粉",
"en": "",
"brand": "禾邁",
"series": "SYNCRON 門板",
"hex": "#d5cdca",
"img": "swatches/hemai/hm_SYM109.jpg",
"thumb": "swatches/hemai/thumb/hm_SYM109.jpg",
"price": 130
},
{
"code": "U129",
"name": "尼羅極致碳黑木紋",
"en": "",
"brand": "禾邁",
"series": "CLEAF",
"hex": "#232325",
"img": "swatches/hemai/hm_U129.jpg",
"thumb": "swatches/hemai/thumb/hm_U129.jpg",
"price": 130
},
{
"code": "UA32",
"name": "格利吉歐淺灰木紋",
"en": "",
"brand": "禾邁",
"series": "CLEAF",
"hex": "#6e6e6e",
"img": "swatches/hemai/hm_UA32.jpg",
"thumb": "swatches/hemai/thumb/hm_UA32.jpg",
"price": 130
},
{
"code": "UA94",
"name": "威松那米灰直紋",
"en": "",
"brand": "禾邁",
"series": "CLEAF",
"hex": "#a29585",
"img": "swatches/hemai/hm_UA94.jpg",
"thumb": "swatches/hemai/thumb/hm_UA94.jpg",
"price": 130
},
{
"code": "UB02",
"name": "意象藍格紋",
"en": "",
"brand": "禾邁",
"series": "CLEAF",
"hex": "#2f3a43",
"img": "swatches/hemai/hm_UB02.jpg",
"thumb": "swatches/hemai/thumb/hm_UB02.jpg",
"price": 130
},
{
"code": "UB07",
"name": "歐瑞那卡其金字塔紋",
"en": "",
"brand": "禾邁",
"series": "CLEAF",
"hex": "#b0a89b",
"img": "swatches/hemai/hm_UB07.jpg",
"thumb": "swatches/hemai/thumb/hm_UB07.jpg",
"price": 130
},
{
"code": "UB18",
"name": "歐蘭修湛橙皮革紋",
"en": "",
"brand": "禾邁",
"series": "CLEAF",
"hex": "#d18244",
"img": "swatches/hemai/hm_UB18.jpg",
"thumb": "swatches/hemai/thumb/hm_UB18.jpg",
"price": 130
},
{
"code": "UB40",
"name": "古蘭西抹茶綠直紋",
"en": "",
"brand": "禾邁",
"series": "CLEAF",
"hex": "#8d8f81",
"img": "swatches/hemai/hm_UB40.jpg",
"thumb": "swatches/hemai/thumb/hm_UB40.jpg",
"price": 130
},
{
"code": "UB53",
"name": "巴勒莫芥末黃直紋",
"en": "",
"brand": "禾邁",
"series": "CLEAF",
"hex": "#d59422",
"img": "swatches/hemai/hm_UB53.jpg",
"thumb": "swatches/hemai/thumb/hm_UB53.jpg",
"price": 130
},
{
"code": "UB54",
"name": "藍柯抹茶綠幾何紋",
"en": "",
"brand": "禾邁",
"series": "CLEAF",
"hex": "#4d503a",
"img": "swatches/hemai/hm_UB54.jpg",
"thumb": "swatches/hemai/thumb/hm_UB54.jpg",
"price": 130
},
{
"code": "024",
"name": "歐蘿卡橡木",
"en": "",
"brand": "禾邁",
"series": "Mauro Saviola",
"hex": "#8e7749",
"img": "swatches/hemai/hm_024.jpg",
"thumb": "swatches/hemai/thumb/hm_024.jpg",
"price": 130
},
{
"code": "045",
"name": "陶瓷米",
"en": "",
"brand": "禾邁",
"series": "KAINDL",
"hex": "#ebdcd2",
"img": "swatches/hemai/hm_045.jpg",
"thumb": "swatches/hemai/thumb/hm_045.jpg",
"price": 130
},
{
"code": "053",
"name": "夢幻黑梣",
"en": "",
"brand": "禾邁",
"series": "ArtDecor",
"hex": "#2b2a2c",
"img": "swatches/hemai/hm_053.jpg",
"thumb": "swatches/hemai/thumb/hm_053.jpg",
"price": 130
},
{
"code": "055",
"name": "熔岩榆木",
"en": "",
"brand": "禾邁",
"series": "KAINDL",
"hex": "#423c3c",
"img": "swatches/hemai/hm_055.jpg",
"thumb": "swatches/hemai/thumb/hm_055.jpg",
"price": 130
},
{
"code": "060",
"name": "白色北歐木",
"en": "",
"brand": "禾邁",
"series": "EGGER",
"hex": "#e2dbdb",
"img": "swatches/hemai/hm_060.jpg",
"thumb": "swatches/hemai/thumb/hm_060.jpg",
"price": 130
},
{
"code": "139",
"name": "聖雷莫砂橡木",
"en": "",
"brand": "禾邁",
"series": "KAINDL",
"hex": "#d7b9a0",
"img": "swatches/hemai/hm_139.jpg",
"thumb": "swatches/hemai/thumb/hm_139.jpg",
"price": 130
},
{
"code": "140",
"name": "經典橡木",
"en": "原廠型號 34140；非現貨",
"brand": "禾邁",
"series": "KAINDL",
"hex": "#a88662",
"img": "swatches/hemai/hm_140.jpg",
"thumb": "swatches/hemai/thumb/hm_140.jpg",
"price": 130
},
{
"code": "143",
"name": "珍珠白榆木",
"en": "",
"brand": "禾邁",
"series": "KAINDL",
"hex": "#e8e6e7",
"img": "swatches/hemai/hm_143.jpg",
"thumb": "swatches/hemai/thumb/hm_143.jpg",
"price": 130
},
{
"code": "禾邁-166",
"name": "陶瓷咖啡",
"en": "",
"brand": "禾邁",
"series": "KAINDL",
"hex": "#8a7c78",
"img": "swatches/hemai/hm_166.jpg",
"thumb": "swatches/hemai/thumb/hm_166.jpg",
"price": 130
},
{
"code": "181",
"name": "法克斯菸草橡木 Hot!",
"en": "",
"brand": "禾邁",
"series": "EGGER",
"hex": "#8e766b",
"img": "swatches/hemai/hm_181.jpg",
"thumb": "swatches/hemai/thumb/hm_181.jpg",
"price": 130
},
{
"code": "210",
"name": "波特蘭白",
"en": "",
"brand": "禾邁",
"series": "Mauro Saviola",
"hex": "#d5d9db",
"img": "swatches/hemai/hm_210.jpg",
"thumb": "swatches/hemai/thumb/hm_210.jpg",
"price": 130
},
{
"code": "267",
"name": "鄉村梣木",
"en": "",
"brand": "禾邁",
"series": "EGGER",
"hex": "#aa998c",
"img": "swatches/hemai/hm_267.jpg",
"thumb": "swatches/hemai/thumb/hm_267.jpg",
"price": 130
},
{
"code": "296",
"name": "珍珠銀狐",
"en": "",
"brand": "禾邁",
"series": "Mauro Saviola",
"hex": "#c9cac6",
"img": "swatches/hemai/hm_296.jpg",
"thumb": "swatches/hemai/thumb/hm_296.jpg",
"price": 130
},
{
"code": "297",
"name": "波特蘭砂岩",
"en": "",
"brand": "禾邁",
"series": "Mauro Saviola",
"hex": "#9e9c97",
"img": "swatches/hemai/hm_297.jpg",
"thumb": "swatches/hemai/thumb/hm_297.jpg",
"price": 130
},
{
"code": "309",
"name": "萊斯頓橡木 Hot!",
"en": "",
"brand": "禾邁",
"series": "EGGER",
"hex": "#b8a292",
"img": "swatches/hemai/hm_309.jpg",
"thumb": "swatches/hemai/thumb/hm_309.jpg",
"price": 130
},
{
"code": "335",
"name": "經典櫸木",
"en": "",
"brand": "禾邁",
"series": "KAINDL",
"hex": "#c5afa0",
"img": "swatches/hemai/hm_335.jpg",
"thumb": "swatches/hemai/thumb/hm_335.jpg",
"price": 130
},
{
"code": "375",
"name": "水泥灰",
"en": "",
"brand": "禾邁",
"series": "KAINDL",
"hex": "#979798",
"img": "swatches/hemai/hm_375.jpg",
"thumb": "swatches/hemai/thumb/hm_375.jpg",
"price": 130
},
{
"code": "425",
"name": "亞麻米布紋",
"en": "",
"brand": "禾邁",
"series": "EGGER",
"hex": "#cec5bf",
"img": "swatches/hemai/hm_425.jpg",
"thumb": "swatches/hemai/thumb/hm_425.jpg",
"price": 130
},
{
"code": "433",
"name": "粉橡木",
"en": "",
"brand": "禾邁",
"series": "Mauro Saviola",
"hex": "#d3c8c6",
"img": "swatches/hemai/hm_433.jpg",
"thumb": "swatches/hemai/thumb/hm_433.jpg",
"price": 130
},
{
"code": "44406",
"name": "皇家水泥白",
"en": "原廠型號 44406DP；非現貨",
"brand": "禾邁",
"series": "KAINDL",
"hex": "#eae3d1",
"img": "swatches/hemai/hm_44406.jpg",
"thumb": "swatches/hemai/thumb/hm_44406.jpg",
"price": 130
},
{
"code": "493",
"name": "亞麻灰布紋",
"en": "",
"brand": "禾邁",
"series": "Mauro Saviola",
"hex": "#b4a9a5",
"img": "swatches/hemai/hm_493.jpg",
"thumb": "swatches/hemai/thumb/hm_493.jpg",
"price": 130
},
{
"code": "570",
"name": "陶瓷白",
"en": "",
"brand": "禾邁",
"series": "KAINDL",
"hex": "#f3f1ee",
"img": "swatches/hemai/hm_570.jpg",
"thumb": "swatches/hemai/thumb/hm_570.jpg",
"price": 130
},
{
"code": "575",
"name": "迪亞曼特白",
"en": "",
"brand": "禾邁",
"series": "KAINDL",
"hex": "#eaeaef",
"img": "swatches/hemai/hm_575.jpg",
"thumb": "swatches/hemai/thumb/hm_575.jpg",
"price": 130
},
{
"code": "577",
"name": "啞光灰 Hot!",
"en": "",
"brand": "禾邁",
"series": "KAINDL",
"hex": "#b7afa2",
"img": "swatches/hemai/hm_577.jpg",
"thumb": "swatches/hemai/thumb/hm_577.jpg",
"price": 130
},
{
"code": "702",
"name": "米灰色羊絨 Hot!",
"en": "",
"brand": "禾邁",
"series": "EGGER",
"hex": "#cdc3b7",
"img": "swatches/hemai/hm_702.jpg",
"thumb": "swatches/hemai/thumb/hm_702.jpg",
"price": 130
},
{
"code": "727",
"name": "石頭灰",
"en": "",
"brand": "禾邁",
"series": "EGGER",
"hex": "#a19386",
"img": "swatches/hemai/hm_727.jpg",
"thumb": "swatches/hemai/thumb/hm_727.jpg",
"price": 130
},
{
"code": "760",
"name": "山形白榆木",
"en": "",
"brand": "禾邁",
"series": "EGGER",
"hex": "#d8cfca",
"img": "swatches/hemai/hm_760.jpg",
"thumb": "swatches/hemai/thumb/hm_760.jpg",
"price": 130
},
{
"code": "769",
"name": "蘇格蘭梣木",
"en": "",
"brand": "禾邁",
"series": "KAINDL",
"hex": "#dbcdbd",
"img": "swatches/hemai/hm_769.jpg",
"thumb": "swatches/hemai/thumb/hm_769.jpg",
"price": 130
},
{
"code": "777",
"name": "落葉松",
"en": "",
"brand": "禾邁",
"series": "KAINDL",
"hex": "#d9baa1",
"img": "swatches/hemai/hm_777.jpg",
"thumb": "swatches/hemai/thumb/hm_777.jpg",
"price": 130
},
{
"code": "797",
"name": "石墨灰",
"en": "",
"brand": "禾邁",
"series": "Mauro Saviola",
"hex": "#4b5052",
"img": "swatches/hemai/hm_797.jpg",
"thumb": "swatches/hemai/thumb/hm_797.jpg",
"price": 130
},
{
"code": "925",
"name": "黑胡桃",
"en": "",
"brand": "禾邁",
"series": "Mauro Saviola",
"hex": "#4e4744",
"img": "swatches/hemai/hm_925.jpg",
"thumb": "swatches/hemai/thumb/hm_925.jpg",
"price": 130
},
{
"code": "禾邁-965",
"name": "蘇格蘭榆木",
"en": "",
"brand": "禾邁",
"series": "KAINDL",
"hex": "#bc9c89",
"img": "swatches/hemai/hm_965.jpg",
"thumb": "swatches/hemai/thumb/hm_965.jpg",
"price": 130
},
{
"code": "禾邁-967",
"name": "皮蒙特櫻桃木",
"en": "",
"brand": "禾邁",
"series": "KAINDL",
"hex": "#865d4f",
"img": "swatches/hemai/hm_967.jpg",
"thumb": "swatches/hemai/thumb/hm_967.jpg",
"price": 130
},
{
"code": "999",
"name": "曜黑松木 Hot!",
"en": "",
"brand": "禾邁",
"series": "EGGER",
"hex": "#35343b",
"img": "swatches/hemai/hm_999.jpg",
"thumb": "swatches/hemai/thumb/hm_999.jpg",
"price": 130
},
{
"code": "D0112",
"name": "淺石灰",
"en": "有白灰線條紋路",
"brand": "禾邁",
"series": "SKIN",
"hex": "#cac9c4",
"img": "swatches/hemai/hm_D0112.jpg",
"thumb": "swatches/hemai/thumb/hm_D0112.jpg",
"price": 130
},
{
"code": "D2124",
"name": "杜卡爾灰",
"en": "",
"brand": "禾邁",
"series": "SKIN",
"hex": "#ccc7c3",
"img": "swatches/hemai/hm_D2124.jpg",
"thumb": "swatches/hemai/thumb/hm_D2124.jpg",
"price": 130
},
{
"code": "D2450",
"name": "維多利亞木 Hot!",
"en": "",
"brand": "禾邁",
"series": "SKIN",
"hex": "#beb7ad",
"img": "swatches/hemai/hm_D2450.jpg",
"thumb": "swatches/hemai/thumb/hm_D2450.jpg",
"price": 130
},
{
"code": "D2451",
"name": "墨勅黑 Hot!",
"en": "",
"brand": "禾邁",
"series": "SKIN",
"hex": "#2c2c2e",
"img": "swatches/hemai/hm_D2451.jpg",
"thumb": "swatches/hemai/thumb/hm_D2451.jpg",
"price": 130
},
{
"code": "D2452",
"name": "白堊岩 Hot!",
"en": "",
"brand": "禾邁",
"series": "SKIN",
"hex": "#cecece",
"img": "swatches/hemai/hm_D2452.jpg",
"thumb": "swatches/hemai/thumb/hm_D2452.jpg",
"price": 130
},
{
"code": "D2479",
"name": "印加棕",
"en": "",
"brand": "禾邁",
"series": "SKIN",
"hex": "#615947",
"img": "swatches/hemai/hm_D2479.jpg",
"thumb": "swatches/hemai/thumb/hm_D2479.jpg",
"price": 130
},
{
"code": "D2480",
"name": "皮拉迪歐灰",
"en": "",
"brand": "禾邁",
"series": "SKIN",
"hex": "#717670",
"img": "swatches/hemai/hm_D2480.jpg",
"thumb": "swatches/hemai/thumb/hm_D2480.jpg",
"price": 130
},
{
"code": "D2481",
"name": "依瑞迪歐咖啡紋",
"en": "",
"brand": "禾邁",
"series": "SKIN",
"hex": "#948f83",
"img": "swatches/hemai/hm_D2481.jpg",
"thumb": "swatches/hemai/thumb/hm_D2481.jpg",
"price": 130
},
{
"code": "D2528",
"name": "坎柏拉灰 Hot!",
"en": "",
"brand": "禾邁",
"series": "SKIN",
"hex": "#979695",
"img": "swatches/hemai/hm_D2528.jpg",
"thumb": "swatches/hemai/thumb/hm_D2528.jpg",
"price": 130
},
{
"code": "D4755",
"name": "羊駝白",
"en": "",
"brand": "禾邁",
"series": "SKIN",
"hex": "#f7f4ef",
"img": "swatches/hemai/hm_D4755.jpg",
"thumb": "swatches/hemai/thumb/hm_D4755.jpg",
"price": 130
},
{
"code": "D4757",
"name": "瑪納鐵灰",
"en": "",
"brand": "禾邁",
"series": "SKIN",
"hex": "#a29c90",
"img": "swatches/hemai/hm_D4757.jpg",
"thumb": "swatches/hemai/thumb/hm_D4757.jpg",
"price": 130
},
{
"code": "D4758",
"name": "吉拉淺泥 Hot!",
"en": "",
"brand": "禾邁",
"series": "SKIN",
"hex": "#a3927a",
"img": "swatches/hemai/hm_D4758.jpg",
"thumb": "swatches/hemai/thumb/hm_D4758.jpg",
"price": 130
},
{
"code": "D4979",
"name": "阿爾多淺織紋",
"en": "",
"brand": "禾邁",
"series": "SKIN",
"hex": "#bab0aa",
"img": "swatches/hemai/hm_D4979.jpg",
"thumb": "swatches/hemai/thumb/hm_D4979.jpg",
"price": 130
},
{
"code": "D4980",
"name": "阿爾多灰織紋",
"en": "",
"brand": "禾邁",
"series": "SKIN",
"hex": "#a59a8f",
"img": "swatches/hemai/hm_D4980.jpg",
"thumb": "swatches/hemai/thumb/hm_D4980.jpg",
"price": 130
},
{
"code": "D4992",
"name": "黃昏飛馬座 Hot!",
"en": "",
"brand": "禾邁",
"series": "SKIN",
"hex": "#574c43",
"img": "swatches/hemai/hm_D4992.jpg",
"thumb": "swatches/hemai/thumb/hm_D4992.jpg",
"price": 130
},
{
"code": "D4994",
"name": "優雅飛馬座 Hot!",
"en": "",
"brand": "禾邁",
"series": "SKIN",
"hex": "#504b44",
"img": "swatches/hemai/hm_D4994.jpg",
"thumb": "swatches/hemai/thumb/hm_D4994.jpg",
"price": 130
},
{
"code": "D5450",
"name": "熔岩黑 Hot!",
"en": "",
"brand": "禾邁",
"series": "SKIN",
"hex": "#423b33",
"img": "swatches/hemai/hm_D5450.jpg",
"thumb": "swatches/hemai/thumb/hm_D5450.jpg",
"price": 130
},
{
"code": "D5451",
"name": "珍珠白",
"en": "有白灰線條紋路",
"brand": "禾邁",
"series": "SKIN",
"hex": "#c9c0b2",
"img": "swatches/hemai/hm_D5451.jpg",
"thumb": "swatches/hemai/thumb/hm_D5451.jpg",
"price": 130
},
{
"code": "D5456",
"name": "青銅岩 Hot!",
"en": "",
"brand": "禾邁",
"series": "SKIN",
"hex": "#695b51",
"img": "swatches/hemai/hm_D5456.jpg",
"thumb": "swatches/hemai/thumb/hm_D5456.jpg",
"price": 130
},
{
"code": "D6572",
"name": "交織淺綠",
"en": "",
"brand": "禾邁",
"series": "SKIN",
"hex": "#c8bcaf",
"img": "swatches/hemai/hm_D6572.jpg",
"thumb": "swatches/hemai/thumb/hm_D6572.jpg",
"price": 130
},
{
"code": "D6577",
"name": "艾姆灰",
"en": "有白灰線條紋路",
"brand": "禾邁",
"series": "SKIN",
"hex": "#c1bab0",
"img": "swatches/hemai/hm_D6577.jpg",
"thumb": "swatches/hemai/thumb/hm_D6577.jpg",
"price": 130
},
{
"code": "D6606",
"name": "塔菲拉榆",
"en": "",
"brand": "禾邁",
"series": "SKIN",
"hex": "#bfac9f",
"img": "swatches/hemai/hm_D6606.jpg",
"thumb": "swatches/hemai/thumb/hm_D6606.jpg",
"price": 130
},
{
"code": "D6679",
"name": "希洛木紋",
"en": "",
"brand": "禾邁",
"series": "SKIN",
"hex": "#e3e0d5",
"img": "swatches/hemai/hm_D6679.jpg",
"thumb": "swatches/hemai/thumb/hm_D6679.jpg",
"price": 130
},
{
"code": "D6680",
"name": "托巴克木紋",
"en": "",
"brand": "禾邁",
"series": "SKIN",
"hex": "#604f42",
"img": "swatches/hemai/hm_D6680.jpg",
"thumb": "swatches/hemai/thumb/hm_D6680.jpg",
"price": 130
},
{
"code": "D6699",
"name": "赫雷斯灰榆",
"en": "",
"brand": "禾邁",
"series": "SKIN",
"hex": "#aca69f",
"img": "swatches/hemai/hm_D6699.jpg",
"thumb": "swatches/hemai/thumb/hm_D6699.jpg",
"price": 130
},
{
"code": "D6739",
"name": "赫雷斯白榆",
"en": "",
"brand": "禾邁",
"series": "SKIN",
"hex": "#deded2",
"img": "swatches/hemai/hm_D6739.jpg",
"thumb": "swatches/hemai/thumb/hm_D6739.jpg",
"price": 130
},
{
"code": "DK570",
"name": "青灰岩 Hot!",
"en": "",
"brand": "禾邁",
"series": "SKIN",
"hex": "#c2c1bf",
"img": "swatches/hemai/hm_DK570.jpg",
"thumb": "swatches/hemai/thumb/hm_DK570.jpg",
"price": 130
},
{
"code": "DK571",
"name": "深灰岩 Hot!",
"en": "",
"brand": "禾邁",
"series": "SKIN",
"hex": "#91908c",
"img": "swatches/hemai/hm_DK571.jpg",
"thumb": "swatches/hemai/thumb/hm_DK571.jpg",
"price": 130
},
{
"code": "DK590",
"name": "凱特木 Hot!",
"en": "",
"brand": "禾邁",
"series": "SKIN",
"hex": "#c5a883",
"img": "swatches/hemai/hm_DK590.jpg",
"thumb": "swatches/hemai/thumb/hm_DK590.jpg",
"price": 130
},
{
"code": "F244",
"name": "碳黑坎德拉大理石",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#5a5858",
"img": "swatches/hemai/hm_F244.jpg",
"thumb": "swatches/hemai/thumb/hm_F244.jpg",
"price": 130
},
{
"code": "F243",
"name": "淺灰坎德拉大理石",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#a9a4a0",
"img": "swatches/hemai/hm_F243.jpg",
"thumb": "swatches/hemai/thumb/hm_F243.jpg",
"price": 130
},
{
"code": "F334",
"name": "亞麻黑灰布紋",
"en": "",
"brand": "禾邁",
"series": "EGGER",
"hex": "#7b756f",
"img": "swatches/hemai/hm_F334.jpg",
"thumb": "swatches/hemai/thumb/hm_F334.jpg",
"price": 130
},
{
"code": "F417",
"name": "灰色布紋",
"en": "",
"brand": "禾邁",
"series": "EGGER",
"hex": "#c5bbaf",
"img": "swatches/hemai/hm_F417.jpg",
"thumb": "swatches/hemai/thumb/hm_F417.jpg",
"price": 130
},
{
"code": "F637",
"name": "水洗清水模",
"en": "",
"brand": "禾邁",
"series": "EGGER",
"hex": "#d8d2c3",
"img": "swatches/hemai/hm_F637.jpg",
"thumb": "swatches/hemai/thumb/hm_F637.jpg",
"price": 130
},
{
"code": "F638",
"name": "銀灰清水模",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#a19890",
"img": "swatches/hemai/hm_F638.jpg",
"thumb": "swatches/hemai/thumb/hm_F638.jpg",
"price": 130
},
{
"code": "F642",
"name": "銅銹清水模",
"en": "",
"brand": "禾邁",
"series": "EGGER",
"hex": "#57504b",
"img": "swatches/hemai/hm_F642.jpg",
"thumb": "swatches/hemai/thumb/hm_F642.jpg",
"price": 130
},
{
"code": "F7025",
"name": "璀璨銀河大理石板",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#525253",
"img": "swatches/hemai/hm_F7025.jpg",
"thumb": "swatches/hemai/thumb/hm_F7025.jpg",
"price": 130
},
{
"code": "F7024",
"name": "金色海岸大理石板",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#b1b2ae",
"img": "swatches/hemai/hm_F7024.jpg",
"thumb": "swatches/hemai/thumb/hm_F7024.jpg",
"price": 130
},
{
"code": "F7021",
"name": "鐵灰砂岩",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#9b998d",
"img": "swatches/hemai/hm_F7021.jpg",
"thumb": "swatches/hemai/thumb/hm_F7021.jpg",
"price": 130
},
{
"code": "F7020",
"name": "網狀斑駁水泥白",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#c5b7ad",
"img": "swatches/hemai/hm_F7020.jpg",
"thumb": "swatches/hemai/thumb/hm_F7020.jpg",
"price": 130
},
{
"code": "F7019",
"name": "淡灰砂岩",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#d5d4cf",
"img": "swatches/hemai/hm_F7019.jpg",
"thumb": "swatches/hemai/thumb/hm_F7019.jpg",
"price": 130
},
{
"code": "F7016",
"name": "阿格羅米布紋",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#d3d0c9",
"img": "swatches/hemai/hm_F7016.jpg",
"thumb": "swatches/hemai/thumb/hm_F7016.jpg",
"price": 130
},
{
"code": "F7013",
"name": "都會亞麻灰織布紋",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#70716b",
"img": "swatches/hemai/hm_F7013.jpg",
"thumb": "swatches/hemai/thumb/hm_F7013.jpg",
"price": 130
},
{
"code": "F7014",
"name": "沙棕棉麻織布紋",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#aea18e",
"img": "swatches/hemai/hm_F7014.jpg",
"thumb": "swatches/hemai/thumb/hm_F7014.jpg",
"price": 130
},
{
"code": "F7023",
"name": "突尼西礦岩黑石板",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#252221",
"img": "swatches/hemai/hm_F7023.jpg",
"thumb": "swatches/hemai/thumb/hm_F7023.jpg",
"price": 130
},
{
"code": "F7029",
"name": "羊絨米灰皮革",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#d6cbc5",
"img": "swatches/hemai/hm_F7029.jpg",
"thumb": "swatches/hemai/thumb/hm_F7029.jpg",
"price": 130
},
{
"code": "F7031",
"name": "石墨黑皮革",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#565251",
"img": "swatches/hemai/hm_F7031.jpg",
"thumb": "swatches/hemai/thumb/hm_F7031.jpg",
"price": 130
},
{
"code": "F7033",
"name": "泥灰刷漆紋",
"en": "",
"brand": "禾邁",
"series": "EGGER",
"hex": "#817871",
"img": "swatches/hemai/hm_F7033.jpg",
"thumb": "swatches/hemai/thumb/hm_F7033.jpg",
"price": 130
},
{
"code": "F7034",
"name": "拿鐵棕皮革",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#7a6e5f",
"img": "swatches/hemai/hm_F7034.jpg",
"thumb": "swatches/hemai/thumb/hm_F7034.jpg",
"price": 130
},
{
"code": "F7035",
"name": "奶茶刷漆紋",
"en": "",
"brand": "禾邁",
"series": "EGGER",
"hex": "#b7a598",
"img": "swatches/hemai/hm_F7035.jpg",
"thumb": "swatches/hemai/thumb/hm_F7035.jpg",
"price": 130
},
{
"code": "F7036",
"name": "白霧金屬刷漆紋",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#bab2a5",
"img": "swatches/hemai/hm_F7036.jpg",
"thumb": "swatches/hemai/thumb/hm_F7036.jpg",
"price": 130
},
{
"code": "F7037",
"name": "銅采金屬刷漆紋",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#666056",
"img": "swatches/hemai/hm_F7037.jpg",
"thumb": "swatches/hemai/thumb/hm_F7037.jpg",
"price": 130
},
{
"code": "F7038",
"name": "星燦白灰岩板",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#aaaaaa",
"img": "swatches/hemai/hm_F7038.jpg",
"thumb": "swatches/hemai/thumb/hm_F7038.jpg",
"price": 130
},
{
"code": "F7039",
"name": "星燦宇宙黑岩板",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#4a4e52",
"img": "swatches/hemai/hm_F7039.jpg",
"thumb": "swatches/hemai/thumb/hm_F7039.jpg",
"price": 130
},
{
"code": "F7052",
"name": "淺灰尼絨布紋",
"en": "",
"brand": "禾邁",
"series": "EGGER",
"hex": "#d7d7d7",
"img": "swatches/hemai/hm_F7052.jpg",
"thumb": "swatches/hemai/thumb/hm_F7052.jpg",
"price": 130
},
{
"code": "F7053",
"name": "岩灰尼絨布紋",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#acacac",
"img": "swatches/hemai/hm_F7053.jpg",
"thumb": "swatches/hemai/thumb/hm_F7053.jpg",
"price": 130
},
{
"code": "F7137",
"name": "灰麻絨質布紋",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#d9d3c5",
"img": "swatches/hemai/hm_F7137.jpg",
"thumb": "swatches/hemai/thumb/hm_F7137.jpg",
"price": 130
},
{
"code": "F7138",
"name": "灰麻絨質布紋",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#b7b0a6",
"img": "swatches/hemai/hm_F7138.jpg",
"thumb": "swatches/hemai/thumb/hm_F7138.jpg",
"price": 130
},
{
"code": "F800",
"name": "卡拉拉大理石板",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#f0eae5",
"img": "swatches/hemai/hm_F800.jpg",
"thumb": "swatches/hemai/thumb/hm_F800.jpg",
"price": 130
},
{
"code": "H007",
"name": "黑布織",
"en": "",
"brand": "禾邁",
"series": "ArtDecor",
"hex": "#4b4746",
"img": "swatches/hemai/hm_H007.jpg",
"thumb": "swatches/hemai/thumb/hm_H007.jpg",
"price": 130
},
{
"code": "H1277",
"name": "淺色萊克蘭刺槐",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#d5c0a4",
"img": "swatches/hemai/hm_H1277.jpg",
"thumb": "swatches/hemai/thumb/hm_H1277.jpg",
"price": 130
},
{
"code": "H1225",
"name": "特倫赫姆梣木",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#ede9e6",
"img": "swatches/hemai/hm_H1225.jpg",
"thumb": "swatches/hemai/thumb/hm_H1225.jpg",
"price": 130
},
{
"code": "H1377",
"name": "奧爾良沙棕橡木 Hot!",
"en": "",
"brand": "禾邁",
"series": "EGGER",
"hex": "#b39b81",
"img": "swatches/hemai/hm_H1377.jpg",
"thumb": "swatches/hemai/thumb/hm_H1377.jpg",
"price": 130
},
{
"code": "H1379",
"name": "奧爾良灰棕橡木",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#79655a",
"img": "swatches/hemai/hm_H1379.jpg",
"thumb": "swatches/hemai/thumb/hm_H1379.jpg",
"price": 130
},
{
"code": "H1385",
"name": "卡塞拉自然橡木",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#b28c65",
"img": "swatches/hemai/hm_H1385.jpg",
"thumb": "swatches/hemai/thumb/hm_H1385.jpg",
"price": 130
},
{
"code": "H1386",
"name": "卡塞拉棕色橡木",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#8c6a4b",
"img": "swatches/hemai/hm_H1386.jpg",
"thumb": "swatches/hemai/thumb/hm_H1386.jpg",
"price": 130
},
{
"code": "H1714",
"name": "林肯胡桃木",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#734f34",
"img": "swatches/hemai/hm_H1714.jpg",
"thumb": "swatches/hemai/thumb/hm_H1714.jpg",
"price": 130
},
{
"code": "H3157",
"name": "消光維琴察橡木",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#c9ae89",
"img": "swatches/hemai/hm_H3157.jpg",
"thumb": "swatches/hemai/thumb/hm_H3157.jpg",
"price": 130
},
{
"code": "H3165",
"name": "淺色維琴察橡木",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#d9c0a6",
"img": "swatches/hemai/hm_H3165.jpg",
"thumb": "swatches/hemai/thumb/hm_H3165.jpg",
"price": 130
},
{
"code": "H3158",
"name": "灰色維琴察橡木",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#988977",
"img": "swatches/hemai/hm_H3158.jpg",
"thumb": "swatches/hemai/thumb/hm_H3158.jpg",
"price": 130
},
{
"code": "H3430",
"name": "米白奧蘭松木",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#d1c1b2",
"img": "swatches/hemai/hm_H3430.jpg",
"thumb": "swatches/hemai/thumb/hm_H3430.jpg",
"price": 130
},
{
"code": "H3433",
"name": "冰白奧蘭松木",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#e5daca",
"img": "swatches/hemai/hm_H3433.jpg",
"thumb": "swatches/hemai/thumb/hm_H3433.jpg",
"price": 130
},
{
"code": "H3311",
"name": "庫內奧洗白橡木",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#d0b090",
"img": "swatches/hemai/hm_H3311.jpg",
"thumb": "swatches/hemai/thumb/hm_H3311.jpg",
"price": 130
},
{
"code": "H3195",
"name": "細絲白木紋",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#eae9e2",
"img": "swatches/hemai/hm_H3195.jpg",
"thumb": "swatches/hemai/thumb/hm_H3195.jpg",
"price": 130
},
{
"code": "H3198",
"name": "細絲深灰木紋",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#635851",
"img": "swatches/hemai/hm_H3198.jpg",
"thumb": "swatches/hemai/thumb/hm_H3198.jpg",
"price": 130
},
{
"code": "H3700",
"name": "鄉村胡桃木",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#af8b68",
"img": "swatches/hemai/hm_H3700.jpg",
"thumb": "swatches/hemai/thumb/hm_H3700.jpg",
"price": 130
},
{
"code": "H3730",
"name": "自然山核桃",
"en": "",
"brand": "禾邁",
"series": "EGGER",
"hex": "#ae8f67",
"img": "swatches/hemai/hm_H3730.jpg",
"thumb": "swatches/hemai/thumb/hm_H3730.jpg",
"price": 130
},
{
"code": "H3785",
"name": "玻利瓦白木紋",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#dcd2c6",
"img": "swatches/hemai/hm_H3785.jpg",
"thumb": "swatches/hemai/thumb/hm_H3785.jpg",
"price": 130
},
{
"code": "H7582",
"name": "焰黯深棕木紋",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#604b42",
"img": "swatches/hemai/hm_H7582.jpg",
"thumb": "swatches/hemai/thumb/hm_H7582.jpg",
"price": 130
},
{
"code": "H7585",
"name": "晨曦金絲木紋",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#aa8c72",
"img": "swatches/hemai/hm_H7585.jpg",
"thumb": "swatches/hemai/thumb/hm_H7585.jpg",
"price": 130
},
{
"code": "K1164",
"name": "法森蠟木",
"en": "",
"brand": "禾邁",
"series": "ArtDecor",
"hex": "#bda88c",
"img": "swatches/hemai/hm_K1164.jpg",
"thumb": "swatches/hemai/thumb/hm_K1164.jpg",
"price": 130
},
{
"code": "K1570",
"name": "鑽石白浮雕",
"en": "原廠型號 1570SU；非現貨",
"brand": "禾邁",
"series": "KAINDL",
"hex": "#f5f4ef",
"img": "swatches/hemai/hm_K1570.jpg",
"thumb": "swatches/hemai/thumb/hm_K1570.jpg",
"price": 130
},
{
"code": "K2824",
"name": "月蝕橡木",
"en": "原廠型號 2824GR；非現貨",
"brand": "禾邁",
"series": "KAINDL",
"hex": "#a29990",
"img": "swatches/hemai/hm_K2824.jpg",
"thumb": "swatches/hemai/thumb/hm_K2824.jpg",
"price": 130
},
{
"code": "K2825",
"name": "日蝕橡木",
"en": "原廠型號 2825GR；非現貨",
"brand": "禾邁",
"series": "KAINDL",
"hex": "#e7e1d3",
"img": "swatches/hemai/hm_K2825.jpg",
"thumb": "swatches/hemai/thumb/hm_K2825.jpg",
"price": 130
},
{
"code": "K2861",
"name": "墨綠灰",
"en": "原廠型號 2861MN；非現貨",
"brand": "禾邁",
"series": "KAINDL",
"hex": "#959b8d",
"img": "swatches/hemai/hm_K2861.jpg",
"thumb": "swatches/hemai/thumb/hm_K2861.jpg",
"price": 130
},
{
"code": "K2860",
"name": "松露奶茶",
"en": "原廠型號 2860MN；非現貨",
"brand": "禾邁",
"series": "KAINDL",
"hex": "#af9c8d",
"img": "swatches/hemai/hm_K2860.jpg",
"thumb": "swatches/hemai/thumb/hm_K2860.jpg",
"price": 130
},
{
"code": "K2872",
"name": "柔霧粉",
"en": "原廠型號 2872MN；非現貨",
"brand": "禾邁",
"series": "KAINDL",
"hex": "#e1cdc6",
"img": "swatches/hemai/hm_K2872.jpg",
"thumb": "swatches/hemai/thumb/hm_K2872.jpg",
"price": 130
},
{
"code": "K3089",
"name": "曉灰皮革紋",
"en": "",
"brand": "禾邁",
"series": "ArtDecor",
"hex": "#6c6359",
"img": "swatches/hemai/hm_K3089.jpg",
"thumb": "swatches/hemai/thumb/hm_K3089.jpg",
"price": 130
},
{
"code": "K3140",
"name": "雪白皮革紋",
"en": "",
"brand": "禾邁",
"series": "ArtDecor",
"hex": "#cfccc4",
"img": "swatches/hemai/hm_K3140.jpg",
"thumb": "swatches/hemai/thumb/hm_K3140.jpg",
"price": 130
},
{
"code": "K4138",
"name": "聖雷莫橡木",
"en": "原廠型號 34138RV；非現貨",
"brand": "禾邁",
"series": "KAINDL",
"hex": "#30261f",
"img": "swatches/hemai/hm_K4138.jpg",
"thumb": "swatches/hemai/thumb/hm_K4138.jpg",
"price": 130
},
{
"code": "K4217",
"name": "芙蓉白橡",
"en": "原廠型號 34217RV；非現貨",
"brand": "禾邁",
"series": "KAINDL",
"hex": "#e8dfd2",
"img": "swatches/hemai/hm_K4217.jpg",
"thumb": "swatches/hemai/thumb/hm_K4217.jpg",
"price": 130
},
{
"code": "K4056",
"name": "板岩栓木",
"en": "原廠型號 34056SU；非現貨",
"brand": "禾邁",
"series": "KAINDL",
"hex": "#ac9681",
"img": "swatches/hemai/hm_K4056.jpg",
"thumb": "swatches/hemai/thumb/hm_K4056.jpg",
"price": 130
},
{
"code": "K4405",
"name": "水泥石板灰",
"en": "原廠型號 4405DP；非現貨",
"brand": "禾邁",
"series": "KAINDL",
"hex": "#666261",
"img": "swatches/hemai/hm_K4405.jpg",
"thumb": "swatches/hemai/thumb/hm_K4405.jpg",
"price": 130
},
{
"code": "K4407",
"name": "水泥白金灰",
"en": "原廠型號 4407DP；非現貨",
"brand": "禾邁",
"series": "KAINDL",
"hex": "#a9a09b",
"img": "swatches/hemai/hm_K4407.jpg",
"thumb": "swatches/hemai/thumb/hm_K4407.jpg",
"price": 130
},
{
"code": "K4892",
"name": "畢耶特拉灰",
"en": "",
"brand": "禾邁",
"series": "KAINDL",
"hex": "#6e6a66",
"img": "swatches/hemai/hm_K4892.jpg",
"thumb": "swatches/hemai/thumb/hm_K4892.jpg",
"price": 130
},
{
"code": "K4895",
"name": "大西洋石墨灰",
"en": "",
"brand": "禾邁",
"series": "KAINDL",
"hex": "#767372",
"img": "swatches/hemai/hm_K4895.jpg",
"thumb": "swatches/hemai/thumb/hm_K4895.jpg",
"price": 130
},
{
"code": "K4946",
"name": "熔岩鐵杉",
"en": "",
"brand": "禾邁",
"series": "KAINDL",
"hex": "#3e3834",
"img": "swatches/hemai/hm_K4946.jpg",
"thumb": "swatches/hemai/thumb/hm_K4946.jpg",
"price": 130
},
{
"code": "K5276",
"name": "桑加洛榆木",
"en": "",
"brand": "禾邁",
"series": "KAINDL",
"hex": "#c2b8ad",
"img": "swatches/hemai/hm_K5276.jpg",
"thumb": "swatches/hemai/thumb/hm_K5276.jpg",
"price": 130
},
{
"code": "K5278",
"name": "聖加洛榆木",
"en": "",
"brand": "禾邁",
"series": "KAINDL",
"hex": "#948370",
"img": "swatches/hemai/hm_K5278.jpg",
"thumb": "swatches/hemai/thumb/hm_K5278.jpg",
"price": 130
},
{
"code": "K5574",
"name": "黃金橡木",
"en": "",
"brand": "禾邁",
"series": "KAINDL",
"hex": "#95724b",
"img": "swatches/hemai/hm_K5574.jpg",
"thumb": "swatches/hemai/thumb/hm_K5574.jpg",
"price": 130
},
{
"code": "K5577",
"name": "黑光石",
"en": "",
"brand": "禾邁",
"series": "KAINDL",
"hex": "#909090",
"img": "swatches/hemai/hm_K5577.jpg",
"thumb": "swatches/hemai/thumb/hm_K5577.jpg",
"price": 130
},
{
"code": "K6358",
"name": "泥灰岩大理石",
"en": "",
"brand": "禾邁",
"series": "ArtDecor",
"hex": "#8f8e90",
"img": "swatches/hemai/hm_K6358.jpg",
"thumb": "swatches/hemai/thumb/hm_K6358.jpg",
"price": 130
},
{
"code": "K9013",
"name": "尊爵金",
"en": "",
"brand": "禾邁",
"series": "ArtDecor",
"hex": "#2c2c2b",
"img": "swatches/hemai/hm_K9013.jpg",
"thumb": "swatches/hemai/thumb/hm_K9013.jpg",
"price": 130
},
{
"code": "U115",
"name": "克拉米色",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#eddec8",
"img": "swatches/hemai/hm_U115.jpg",
"thumb": "swatches/hemai/thumb/hm_U115.jpg",
"price": 130
},
{
"code": "U325",
"name": "復古玫瑰",
"en": "",
"brand": "禾邁",
"series": "EGGER",
"hex": "#c39d94",
"img": "swatches/hemai/hm_U325.jpg",
"thumb": "swatches/hemai/thumb/hm_U325.jpg",
"price": 130
},
{
"code": "U603",
"name": "翡翠綠",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#d6d6be",
"img": "swatches/hemai/hm_U603.jpg",
"thumb": "swatches/hemai/thumb/hm_U603.jpg",
"price": 130
},
{
"code": "U504",
"name": "蒂羅爾藍",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#454e5d",
"img": "swatches/hemai/hm_U504.jpg",
"thumb": "swatches/hemai/thumb/hm_U504.jpg",
"price": 130
},
{
"code": "U604",
"name": "蘆葦綠",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#737e70",
"img": "swatches/hemai/hm_U604.jpg",
"thumb": "swatches/hemai/thumb/hm_U604.jpg",
"price": 130
},
{
"code": "U636",
"name": "海灣綠",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#8d8f8c",
"img": "swatches/hemai/hm_U636.jpg",
"thumb": "swatches/hemai/thumb/hm_U636.jpg",
"price": 130
},
{
"code": "U732",
"name": "深灰色",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#838582",
"img": "swatches/hemai/hm_U732.jpg",
"thumb": "swatches/hemai/thumb/hm_U732.jpg",
"price": 130
},
{
"code": "U705",
"name": "安哥拉灰",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#e4dcd1",
"img": "swatches/hemai/hm_U705.jpg",
"thumb": "swatches/hemai/thumb/hm_U705.jpg",
"price": 130
},
{
"code": "U708",
"name": "淺灰色",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#cfccc7",
"img": "swatches/hemai/hm_U708.jpg",
"thumb": "swatches/hemai/thumb/hm_U708.jpg",
"price": 130
},
{
"code": "U780",
"name": "花崗岩灰",
"en": "",
"brand": "禾邁",
"series": "EGGER",
"hex": "#70777d",
"img": "swatches/hemai/hm_U780.jpg",
"thumb": "swatches/hemai/thumb/hm_U780.jpg",
"price": 130
},
{
"code": "U968",
"name": "碳灰色",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#3c3837",
"img": "swatches/hemai/hm_U968.jpg",
"thumb": "swatches/hemai/thumb/hm_U968.jpg",
"price": 130
},
{
"code": "U999",
"name": "消光同步曜黑木紋",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#0f0f11",
"img": "swatches/hemai/hm_U999.jpg",
"thumb": "swatches/hemai/thumb/hm_U999.jpg",
"price": 130
},
{
"code": "W1000",
"name": "消光木紋白",
"en": "非現貨",
"brand": "禾邁",
"series": "EGGER",
"hex": "#f1ede5",
"img": "swatches/hemai/hm_W1000.jpg",
"thumb": "swatches/hemai/thumb/hm_W1000.jpg",
"price": 130
},
{
"code": "W952",
"name": "優質白",
"en": "",
"brand": "禾邁",
"series": "EGGER",
"hex": "#f7f6f1",
"img": "swatches/hemai/hm_W952.jpg",
"thumb": "swatches/hemai/thumb/hm_W952.jpg",
"price": 130
}
]);
