/* 石英石／燒結石色板：愷薩金石 Caesarstone（caesarstone.com.tw）、帝通石 Dekton（silestone.coallmax.com 興立富）、耐麗石 Neolith（twneoreach.com 興立富），2026/10 下載；640x400 貼圖在 swatches/caesarstone|dekton|neolith/、縮圖在 thumb/
   單價為暫定參考（石英石檯面行情約 200～350 元/cm ≈ 3,000～5,400 元/才），請於「板材售價」修改；賽麗石 Silestone 另見 swatches-silestone.js */
window.SWATCHES = (window.SWATCHES || []).concat([
{
"code": "CS5152",
"name": "金絲雀 Goldfinch",
"en": "Caesarstone 超自然系列｜拋光面｜330*160*1.3 cm　石英石　台灣官網色卡　官網未標價，暫定 3,800 元/才",
"brand": "愷薩金石 Caesarstone",
"series": "超自然系列",
"hex": "#f1f0e4",
"img": "swatches/caesarstone/cs_CS5152.jpg",
"thumb": "swatches/caesarstone/thumb/cs_CS5152.jpg",
"price": 3800,
"top": true
},
{
"code": "CS4601",
"name": "冰水磨石 Frozen Terra",
"en": "Caesarstone 經典系列｜啞光面｜300*140*1.3 cm　石英石　台灣官網色卡　官網未標價，暫定 3,800 元/才",
"brand": "愷薩金石 Caesarstone",
"series": "經典系列",
"hex": "#c9c6bd",
"img": "swatches/caesarstone/cs_CS4601.jpg",
"thumb": "swatches/caesarstone/thumb/cs_CS4601.jpg",
"price": 3800,
"top": true
},
{
"code": "CS4001",
"name": "新晨曦 Fresh Concrete",
"en": "Caesarstone 經典系列｜啞光面｜300*140*1.3 cm　石英石　台灣官網色卡　官網未標價，暫定 3,800 元/才",
"brand": "愷薩金石 Caesarstone",
"series": "經典系列",
"hex": "#dad8d1",
"img": "swatches/caesarstone/cs_CS4001.jpg",
"thumb": "swatches/caesarstone/thumb/cs_CS4001.jpg",
"price": 3800,
"top": true
},
{
"code": "CS4003",
"name": "新水凝灰 Sleek Concrete",
"en": "Caesarstone 經典系列｜啞光面｜300*140*1.3 cm　石英石　台灣官網色卡　官網未標價，暫定 3,800 元/才",
"brand": "愷薩金石 Caesarstone",
"series": "經典系列",
"hex": "#a09693",
"img": "swatches/caesarstone/cs_CS4003.jpg",
"thumb": "swatches/caesarstone/thumb/cs_CS4003.jpg",
"price": 3800,
"top": true
},
{
"code": "CS4030",
"name": "生蠔 Oyster",
"en": "Caesarstone 經典系列｜拋光面｜300*140*1.3 cm　石英石　台灣官網色卡　官網未標價，暫定 3,800 元/才",
"brand": "愷薩金石 Caesarstone",
"series": "經典系列",
"hex": "#898a83",
"img": "swatches/caesarstone/cs_CS4030.jpg",
"thumb": "swatches/caesarstone/thumb/cs_CS4030.jpg",
"price": 3800,
"top": true
},
{
"code": "CS4600",
"name": "棉白 Organic White",
"en": "Caesarstone 經典系列｜拋光面｜320*160*1.3cm　石英石　台灣官網色卡　官網未標價，暫定 3,800 元/才",
"brand": "愷薩金石 Caesarstone",
"series": "經典系列",
"hex": "#f1eee7",
"img": "swatches/caesarstone/cs_CS4600.jpg",
"thumb": "swatches/caesarstone/thumb/cs_CS4600.jpg",
"price": 3800,
"top": true
},
{
"code": "CS3141",
"name": "天鵝絨 Osprey",
"en": "Caesarstone 經典系列｜拋光面｜300*140*1.3 cm　石英石　台灣官網色卡　官網未標價，暫定 3,800 元/才",
"brand": "愷薩金石 Caesarstone",
"series": "經典系列",
"hex": "#ecece2",
"img": "swatches/caesarstone/cs_CS3141.jpg",
"thumb": "swatches/caesarstone/thumb/cs_CS3141.jpg",
"price": 3800,
"top": true
},
{
"code": "CS2003",
"name": "鈦金灰 Concrete",
"en": "Caesarstone 經典系列｜拋光面｜300*140*1.3 cm　石英石　台灣官網色卡　官網未標價，暫定 3,800 元/才",
"brand": "愷薩金石 Caesarstone",
"series": "經典系列",
"hex": "#64615c",
"img": "swatches/caesarstone/cs_CS2003.jpg",
"thumb": "swatches/caesarstone/thumb/cs_CS2003.jpg",
"price": 3800,
"top": true
},
{
"code": "CS3100",
"name": "極地黑 Jet Black",
"en": "Caesarstone 經典系列｜拋光面｜300*140*1.3 cm　石英石　台灣官網色卡　官網未標價，暫定 3,800 元/才",
"brand": "愷薩金石 Caesarstone",
"series": "經典系列",
"hex": "#1f1c17",
"img": "swatches/caesarstone/cs_CS3100.jpg",
"thumb": "swatches/caesarstone/thumb/cs_CS3100.jpg",
"price": 3800,
"top": true
},
{
"code": "CS1141",
"name": "極品白 Pure White",
"en": "Caesarstone 經典系列｜拋光面｜300*140*1.3 cm　石英石　台灣官網色卡　官網未標價，暫定 3,800 元/才",
"brand": "愷薩金石 Caesarstone",
"series": "經典系列",
"hex": "#f4f5f0",
"img": "swatches/caesarstone/cs_CS1141.jpg",
"thumb": "swatches/caesarstone/thumb/cs_CS1141.jpg",
"price": 3800,
"top": true
},
{
"code": "CS4044",
"name": "天際 Airy Concrete",
"en": "Caesarstone 超自然系列｜地表面｜330*160*1.3 cm　石英石　台灣官網色卡　官網未標價，暫定 3,800 元/才",
"brand": "愷薩金石 Caesarstone",
"series": "超自然系列",
"hex": "#95959b",
"img": "swatches/caesarstone/cs_CS4044.jpg",
"thumb": "swatches/caesarstone/thumb/cs_CS4044.jpg",
"price": 3800,
"top": true
},
{
"code": "CS4011",
"name": "水星 Cloudburst Concrete",
"en": "Caesarstone 超自然系列｜地表面｜330*160*1.3 cm　石英石　台灣官網色卡　官網未標價，暫定 3,800 元/才",
"brand": "愷薩金石 Caesarstone",
"series": "超自然系列",
"hex": "#d6d3c6",
"img": "swatches/caesarstone/cs_CS4011.jpg",
"thumb": "swatches/caesarstone/thumb/cs_CS4011.jpg",
"price": 3800,
"top": true
},
{
"code": "CS3100C",
"name": "黑鱷魚 Black Crocodile",
"en": "Caesarstone 停產色｜雕花系列｜雕花面｜300*140*1.3 cm　石英石　台灣官網色卡　官網未標價，暫定 3,800 元/才",
"brand": "愷薩金石 Caesarstone",
"series": "停產色｜雕花系列",
"hex": "#1b1b1b",
"img": "swatches/caesarstone/cs_CS3100C.jpg",
"thumb": "swatches/caesarstone/thumb/cs_CS3100C.jpg",
"price": 3800,
"top": true
},
{
"code": "CS2141C",
"name": "白鱷魚 White Crocodile",
"en": "Caesarstone 停產色｜雕花系列｜雕花面｜300*140*1.3 cm　石英石　台灣官網色卡　官網未標價，暫定 3,800 元/才",
"brand": "愷薩金石 Caesarstone",
"series": "停產色｜雕花系列",
"hex": "#d8d8d8",
"img": "swatches/caesarstone/cs_CS2141C.jpg",
"thumb": "swatches/caesarstone/thumb/cs_CS2141C.jpg",
"price": 3800,
"top": true
},
{
"code": "CS2141L",
"name": "白蕾絲 Lace",
"en": "Caesarstone 停產色｜雕花系列｜雕花面｜300*140*1.3 cm　石英石　台灣官網色卡　官網未標價，暫定 3,800 元/才",
"brand": "愷薩金石 Caesarstone",
"series": "停產色｜雕花系列",
"hex": "#e4ebe4",
"img": "swatches/caesarstone/cs_CS2141L.jpg",
"thumb": "swatches/caesarstone/thumb/cs_CS2141L.jpg",
"price": 3800,
"top": true
},
{
"code": "CS4033",
"name": "地表 Rugged Concrete",
"en": "Caesarstone 超自然系列｜地表面｜330*160*1.3 cm　石英石　台灣官網色卡　官網未標價，暫定 3,800 元/才",
"brand": "愷薩金石 Caesarstone",
"series": "超自然系列",
"hex": "#505251",
"img": "swatches/caesarstone/cs_CS4033.jpg",
"thumb": "swatches/caesarstone/thumb/cs_CS4033.jpg",
"price": 3800,
"top": true
},
{
"code": "CS4046",
"name": "熔岩 Excava",
"en": "Caesarstone 超自然系列｜地表面｜330*160*1.3　石英石　台灣官網色卡　官網未標價，暫定 3,800 元/才",
"brand": "愷薩金石 Caesarstone",
"series": "超自然系列",
"hex": "#9c958c",
"img": "swatches/caesarstone/cs_CS4046.jpg",
"thumb": "swatches/caesarstone/thumb/cs_CS4046.jpg",
"price": 3800,
"top": true
},
{
"code": "CS5810",
"name": "隱仕 Black Tempal",
"en": "Caesarstone 超自然系列｜自然面｜330*160*1.3 cm　石英石　台灣官網色卡　官網未標價，暫定 3,800 元/才",
"brand": "愷薩金石 Caesarstone",
"series": "超自然系列",
"hex": "#233335",
"img": "swatches/caesarstone/cs_CS5810.jpg",
"thumb": "swatches/caesarstone/thumb/cs_CS5810.jpg",
"price": 3800,
"top": true
},
{
"code": "CS5171",
"name": "艾拉貝圖 Arabetto",
"en": "Caesarstone 超自然系列｜拋光面｜330*160*1.3 cm　石英石　台灣官網色卡　官網未標價，暫定 3,800 元/才",
"brand": "愷薩金石 Caesarstone",
"series": "超自然系列",
"hex": "#e4e4d8",
"img": "swatches/caesarstone/cs_CS5171.jpg",
"thumb": "swatches/caesarstone/thumb/cs_CS5171.jpg",
"price": 3800,
"top": true
},
{
"code": "CS6131",
"name": "晶沙灰 Bianco Drift",
"en": "Caesarstone 超自然系列｜拋光面｜300*140*1.3 cm　石英石　台灣官網色卡　官網未標價，暫定 3,800 元/才",
"brand": "愷薩金石 Caesarstone",
"series": "超自然系列",
"hex": "#ced0c4",
"img": "swatches/caesarstone/cs_CS6131.jpg",
"thumb": "swatches/caesarstone/thumb/cs_CS6131.jpg",
"price": 3800,
"top": true
},
{
"code": "CS5110",
"name": "雲霧 Alpine Mist",
"en": "Caesarstone 超自然系列｜拋光面｜300*140*1.3 cm　石英石　台灣官網色卡　官網未標價，暫定 3,800 元/才",
"brand": "愷薩金石 Caesarstone",
"series": "超自然系列",
"hex": "#e1e1db",
"img": "swatches/caesarstone/cs_CS5110.jpg",
"thumb": "swatches/caesarstone/thumb/cs_CS5110.jpg",
"price": 3800,
"top": true
},
{
"code": "CS5100",
"name": "香草黑 Vanilla Noir",
"en": "Caesarstone 超自然系列｜拋光面｜300*140*1.3 cm　石英石　台灣官網色卡　官網未標價，暫定 3,800 元/才",
"brand": "愷薩金石 Caesarstone",
"series": "超自然系列",
"hex": "#1d1a15",
"img": "swatches/caesarstone/cs_CS5100.jpg",
"thumb": "swatches/caesarstone/thumb/cs_CS5100.jpg",
"price": 3800,
"top": true
},
{
"code": "CS5043",
"name": "萬寶龍 Montblanc",
"en": "Caesarstone 超自然系列｜拋光面｜300*140*2 cm　石英石　台灣官網色卡　官網未標價，暫定 3,800 元/才",
"brand": "愷薩金石 Caesarstone",
"series": "超自然系列",
"hex": "#cfd0c9",
"img": "swatches/caesarstone/cs_CS5043.jpg",
"thumb": "swatches/caesarstone/thumb/cs_CS5043.jpg",
"price": 3800,
"top": true
},
{
"code": "CS6338",
"name": "林地 Woodland",
"en": "Caesarstone 超自然系列｜拋光面｜300*140*1.3 cm　石英石　台灣官網色卡　官網未標價，暫定 3,800 元/才",
"brand": "愷薩金石 Caesarstone",
"series": "超自然系列",
"hex": "#2e231c",
"img": "swatches/caesarstone/cs_CS6338.jpg",
"thumb": "swatches/caesarstone/thumb/cs_CS6338.jpg",
"price": 3800,
"top": true
},
{
"code": "CS5141",
"name": "卡琳娜冰川 Frosty Carrina",
"en": "Caesarstone 超自然系列｜拋光面｜330*160*1.3 cm　石英石　台灣官網色卡　官網未標價，暫定 3,800 元/才",
"brand": "愷薩金石 Caesarstone",
"series": "超自然系列",
"hex": "#edede7",
"img": "swatches/caesarstone/cs_CS5141.jpg",
"thumb": "swatches/caesarstone/thumb/cs_CS5141.jpg",
"price": 3800,
"top": true
},
{
"code": "CS5003",
"name": "比亞特灰 Piatra Grey",
"en": "Caesarstone 超自然系列｜拋光面｜300*140*1.3 cm　石英石　台灣官網色卡　官網未標價，暫定 3,800 元/才",
"brand": "愷薩金石 Caesarstone",
"series": "超自然系列",
"hex": "#524f48",
"img": "swatches/caesarstone/cs_CS5003.jpg",
"thumb": "swatches/caesarstone/thumb/cs_CS5003.jpg",
"price": 3800,
"top": true
},
{
"code": "DT1001",
"name": "黛娜米黃 Danae",
"en": "Dekton 燒結石（超薄岩板）　興立富台灣色卡　型號：DT1001 (0.8cm), DT101　官網未標價，暫定 5,000 元/才",
"brand": "帝通石 Dekton",
"series": "燒結石",
"hex": "#cdbfb3",
"img": "swatches/dekton/dk_DT1001.jpg",
"thumb": "swatches/dekton/thumb/dk_DT1001.jpg",
"price": 5000,
"top": true
},
{
"code": "DT1002",
"name": "黑檀 Sirius",
"en": "Dekton 燒結石（超薄岩板）　興立富台灣色卡　型號：DT1002 (0.8cm), DT102　官網未標價，暫定 5,000 元/才",
"brand": "帝通石 Dekton",
"series": "燒結石",
"hex": "#262625",
"img": "swatches/dekton/dk_DT1002.jpg",
"thumb": "swatches/dekton/thumb/dk_DT1002.jpg",
"price": 5000,
"top": true
},
{
"code": "DT1004",
"name": "雪山灰 Sirocco",
"en": "Dekton 燒結石（超薄岩板）　興立富台灣色卡　型號：DT1004, DT8104　官網未標價，暫定 5,000 元/才",
"brand": "帝通石 Dekton",
"series": "燒結石",
"hex": "#9c968b",
"img": "swatches/dekton/dk_DT1004.jpg",
"thumb": "swatches/dekton/thumb/dk_DT1004.jpg",
"price": 5000,
"top": true
},
{
"code": "DT4108",
"name": "淺沙士 Sasea",
"en": "Dekton 燒結石（超薄岩板）　興立富台灣色卡　型號：DT4108, DT4108 (0.4cm), DT108　官網未標價，暫定 5,000 元/才",
"brand": "帝通石 Dekton",
"series": "燒結石",
"hex": "#e7e1cd",
"img": "swatches/dekton/dk_DT4108.jpg",
"thumb": "swatches/dekton/thumb/dk_DT4108.jpg",
"price": 5000,
"top": true
},
{
"code": "DT4111",
"name": "愛麗石 Aeris",
"en": "Dekton 燒結石（超薄岩板）　興立富台灣色卡　型號：DT4111 (0.4cm), DT1011 (0.8cm), DT111　官網未標價，暫定 5,000 元/才",
"brand": "帝通石 Dekton",
"series": "燒結石",
"hex": "#d7d2cc",
"img": "swatches/dekton/dk_DT4111.jpg",
"thumb": "swatches/dekton/thumb/dk_DT4111.jpg",
"price": 5000,
"top": true
},
{
"code": "DT4112",
"name": "暗黑石 Eter",
"en": "Dekton 燒結石（超薄岩板）　興立富台灣色卡　型號：DT4112 (0.4cm), DT1012 (0.8cm), DT112　官網未標價，暫定 5,000 元/才",
"brand": "帝通石 Dekton",
"series": "燒結石",
"hex": "#3b3b3b",
"img": "swatches/dekton/dk_DT4112.jpg",
"thumb": "swatches/dekton/thumb/dk_DT4112.jpg",
"price": 5000,
"top": true
},
{
"code": "DT202",
"name": "金輪黑 Domoos",
"en": "Dekton 燒結石（超薄岩板）　興立富台灣色卡　型號：DT202　官網未標價，暫定 5,000 元/才",
"brand": "帝通石 Dekton",
"series": "燒結石",
"hex": "#0e0f0a",
"img": "swatches/dekton/dk_DT202.jpg",
"thumb": "swatches/dekton/thumb/dk_DT202.jpg",
"price": 5000,
"top": true
},
{
"code": "DT2003",
"name": "紫檀 Keranium",
"en": "Dekton 燒結石（超薄岩板）　興立富台灣色卡　型號：DT2003 (0.8cm), DT8203 (2.0cm)　官網未標價，暫定 5,000 元/才",
"brand": "帝通石 Dekton",
"series": "燒結石",
"hex": "#483b2f",
"img": "swatches/dekton/dk_DT2003.jpg",
"thumb": "swatches/dekton/thumb/dk_DT2003.jpg",
"price": 5000,
"top": true
},
{
"code": "DT2004",
"name": "黑金木紋 Ananke",
"en": "Dekton 燒結石（超薄岩板）　興立富台灣色卡　型號：DT2004 (0.8cm)　官網未標價，暫定 5,000 元/才",
"brand": "帝通石 Dekton",
"series": "燒結石",
"hex": "#1d1a17",
"img": "swatches/dekton/dk_DT2004.jpg",
"thumb": "swatches/dekton/thumb/dk_DT2004.jpg",
"price": 5000,
"top": true
},
{
"code": "DT4206",
"name": "龍紋石 Kelya",
"en": "Dekton 燒結石（超薄岩板）　興立富台灣色卡　型號：DT4206 (0.4cm), DT2006 (0.8cm), DT206, DT8206 (2.0cm)　官網未標價，暫定 5,000 元/才",
"brand": "帝通石 Dekton",
"series": "燒結石",
"hex": "#232120",
"img": "swatches/dekton/dk_DT4206.jpg",
"thumb": "swatches/dekton/thumb/dk_DT4206.jpg",
"price": 5000,
"top": true
},
{
"code": "DT4208",
"name": "黑芝麻 Keon",
"en": "Dekton 燒結石（超薄岩板）　興立富台灣色卡　型號：DT4208 (0.4cm), DT2008 (0.8cm), DT208, DT2008　官網未標價，暫定 5,000 元/才",
"brand": "帝通石 Dekton",
"series": "燒結石",
"hex": "#959288",
"img": "swatches/dekton/dk_DT4208.jpg",
"thumb": "swatches/dekton/thumb/dk_DT4208.jpg",
"price": 5000,
"top": true
},
{
"code": "DT8211",
"name": "黃葉石 Valterra",
"en": "Dekton 燒結石（超薄岩板）　興立富台灣色卡　型號：DT8211 (1.2cm), DT8211 (2.0cm)　官網未標價，暫定 5,000 元/才",
"brand": "帝通石 Dekton",
"series": "燒結石",
"hex": "#bd9c77",
"img": "swatches/dekton/dk_DT8211.jpg",
"thumb": "swatches/dekton/thumb/dk_DT8211.jpg",
"price": 5000,
"top": true
},
{
"code": "DT4215",
"name": "玉筋石 Nilium",
"en": "Dekton 燒結石（超薄岩板）　興立富台灣色卡　型號：DT4215 (0.4cm), DT2015 (0.8cm), DT215, DT8215 (2.0cm)　官網未標價，暫定 5,000 元/才",
"brand": "帝通石 Dekton",
"series": "燒結石",
"hex": "#edeae2",
"img": "swatches/dekton/dk_DT4215.jpg",
"thumb": "swatches/dekton/thumb/dk_DT4215.jpg",
"price": 5000,
"top": true
},
{
"code": "DT2018",
"name": "吉拉咖啡 Kira",
"en": "Dekton 燒結石（超薄岩板）　興立富台灣色卡　型號：DT2018 (0.8cm), DT218, DT8218 (2.0cm)　官網未標價，暫定 5,000 元/才",
"brand": "帝通石 Dekton",
"series": "燒結石",
"hex": "#6b625c",
"img": "swatches/dekton/dk_DT2018.jpg",
"thumb": "swatches/dekton/thumb/dk_DT2018.jpg",
"price": 5000,
"top": true
},
{
"code": "DT4219",
"name": "薇拉灰 Vera",
"en": "Dekton 燒結石（超薄岩板）　興立富台灣色卡　型號：DT4219 (0.4cm)　官網未標價，暫定 5,000 元/才",
"brand": "帝通石 Dekton",
"series": "燒結石",
"hex": "#9a9a9a",
"img": "swatches/dekton/dk_DT4219.jpg",
"thumb": "swatches/dekton/thumb/dk_DT4219.jpg",
"price": 5000,
"top": true
},
{
"code": "DT4220",
"name": "島嶼灰 Kreta",
"en": "Dekton 燒結石（超薄岩板）　興立富台灣色卡　型號：DT4220 (0.4cm), DT2020 (0.8cm), DT220　官網未標價，暫定 5,000 元/才",
"brand": "帝通石 Dekton",
"series": "燒結石",
"hex": "#a9a4a3",
"img": "swatches/dekton/dk_DT4220.jpg",
"thumb": "swatches/dekton/thumb/dk_DT4220.jpg",
"price": 5000,
"top": true
},
{
"code": "DT4221",
"name": "老撾淺黑 Laos",
"en": "Dekton 燒結石（超薄岩板）　興立富台灣色卡　型號：DT4221 (0.4cm), DT2021 (0.8cm), DT221　官網未標價，暫定 5,000 元/才",
"brand": "帝通石 Dekton",
"series": "燒結石",
"hex": "#504d4d",
"img": "swatches/dekton/dk_DT4221.jpg",
"thumb": "swatches/dekton/thumb/dk_DT4221.jpg",
"price": 5000,
"top": true
},
{
"code": "DT4222",
"name": "月暈石 Lunar",
"en": "Dekton 燒結石（超薄岩板）　興立富台灣色卡　型號：DT4222 (0.4cm), DT2022 (0.8cm), DT222　官網未標價，暫定 5,000 元/才",
"brand": "帝通石 Dekton",
"series": "燒結石",
"hex": "#dedbd1",
"img": "swatches/dekton/dk_DT4222.jpg",
"thumb": "swatches/dekton/thumb/dk_DT4222.jpg",
"price": 5000,
"top": true
},
{
"code": "DT2023",
"name": "蒐卡灰 Soke",
"en": "Dekton 燒結石（超薄岩板）　興立富台灣色卡　型號：DT2023 (0.8cm)　官網未標價，暫定 5,000 元/才",
"brand": "帝通石 Dekton",
"series": "燒結石",
"hex": "#a4a09c",
"img": "swatches/dekton/dk_DT2023.jpg",
"thumb": "swatches/dekton/thumb/dk_DT2023.jpg",
"price": 5000,
"top": true
},
{
"code": "DT2025",
"name": "蚵灰石 Kovik",
"en": "Dekton 燒結石（超薄岩板）　興立富台灣色卡　型號：DT2025 (0.8cm), DT225　官網未標價，暫定 5,000 元/才",
"brand": "帝通石 Dekton",
"series": "燒結石",
"hex": "#acaca8",
"img": "swatches/dekton/dk_DT2025.jpg",
"thumb": "swatches/dekton/thumb/dk_DT2025.jpg",
"price": 5000,
"top": true
},
{
"code": "DT4226",
"name": "石膏白 Albarium",
"en": "Dekton 燒結石（超薄岩板）　興立富台灣色卡　型號：DT4226 (0.4cm), DT2026 (0.8cm), DT226, DT8226 (2.0cm)　官網未標價，暫定 5,000 元/才",
"brand": "帝通石 Dekton",
"series": "燒結石",
"hex": "#d5d1c8",
"img": "swatches/dekton/dk_DT4226.jpg",
"thumb": "swatches/dekton/thumb/dk_DT4226.jpg",
"price": 5000,
"top": true
},
{
"code": "DT4227",
"name": "珍珠米黃 Nacre",
"en": "Dekton 燒結石（超薄岩板）　興立富台灣色卡　型號：DT4227 (0.4cm), DT2027 (0.8cm), DT227　官網未標價，暫定 5,000 元/才",
"brand": "帝通石 Dekton",
"series": "燒結石",
"hex": "#dfd4c1",
"img": "swatches/dekton/dk_DT4227.jpg",
"thumb": "swatches/dekton/thumb/dk_DT4227.jpg",
"price": 5000,
"top": true
},
{
"code": "DT4228",
"name": "琥珀棕 Umber",
"en": "Dekton 燒結石（超薄岩板）　興立富台灣色卡　型號：DT4228 (0.4cm), DT2028 (0.8cm), DT228　官網未標價，暫定 5,000 元/才",
"brand": "帝通石 Dekton",
"series": "燒結石",
"hex": "#ae7c67",
"img": "swatches/dekton/dk_DT4228.jpg",
"thumb": "swatches/dekton/thumb/dk_DT4228.jpg",
"price": 5000,
"top": true
},
{
"code": "DT2029",
"name": "鍺灰石 Argentium",
"en": "Dekton 燒結石（超薄岩板）　興立富台灣色卡　型號：DT2029 (0.8cm), DT229　官網未標價，暫定 5,000 元/才",
"brand": "帝通石 Dekton",
"series": "燒結石",
"hex": "#c5c1b6",
"img": "swatches/dekton/dk_DT2029.jpg",
"thumb": "swatches/dekton/thumb/dk_DT2029.jpg",
"price": 5000,
"top": true
},
{
"code": "DT4230",
"name": "浪花石 Marina",
"en": "Dekton 燒結石（超薄岩板）　興立富台灣色卡　型號：DT4230 (0.4cm), DT2030 (0.8cm), DT230　官網未標價，暫定 5,000 元/才",
"brand": "帝通石 Dekton",
"series": "燒結石",
"hex": "#ededec",
"img": "swatches/dekton/dk_DT4230.jpg",
"thumb": "swatches/dekton/thumb/dk_DT4230.jpg",
"price": 5000,
"top": true
},
{
"code": "DT4231",
"name": "冷霜米黃 Nebbia",
"en": "Dekton 燒結石（超薄岩板）　興立富台灣色卡　型號：DT4231 (0.4cm), DT2031 (0.8cm), DT231　官網未標價，暫定 5,000 元/才",
"brand": "帝通石 Dekton",
"series": "燒結石",
"hex": "#cbc5be",
"img": "swatches/dekton/dk_DT4231.jpg",
"thumb": "swatches/dekton/thumb/dk_DT4231.jpg",
"price": 5000,
"top": true
},
{
"code": "DT4232",
"name": "象牙米黃 Avorio",
"en": "Dekton 燒結石（超薄岩板）　興立富台灣色卡　型號：DT4232 (0.4cm), DT2032 (0.8cm), DT4232 (1.2cm)　官網未標價，暫定 5,000 元/才",
"brand": "帝通石 Dekton",
"series": "燒結石",
"hex": "#c7beaf",
"img": "swatches/dekton/dk_DT4232.jpg",
"thumb": "swatches/dekton/thumb/dk_DT4232.jpg",
"price": 5000,
"top": true
},
{
"code": "DT4233",
"name": "皮諾淺灰 Grigio",
"en": "Dekton 燒結石（超薄岩板）　興立富台灣色卡　型號：DT4233 (0.4cm), DT233　官網未標價，暫定 5,000 元/才",
"brand": "帝通石 Dekton",
"series": "燒結石",
"hex": "#a19a90",
"img": "swatches/dekton/dk_DT4233.jpg",
"thumb": "swatches/dekton/thumb/dk_DT4233.jpg",
"price": 5000,
"top": true
},
{
"code": "DT4234",
"name": "撥墨深灰 Grafite",
"en": "Dekton 燒結石（超薄岩板）　興立富台灣色卡　型號：DT4234 (0.4cm), DT2034 (0.8cm), DT234　官網未標價，暫定 5,000 元/才",
"brand": "帝通石 Dekton",
"series": "燒結石",
"hex": "#6e6c6c",
"img": "swatches/dekton/dk_DT4234.jpg",
"thumb": "swatches/dekton/thumb/dk_DT4234.jpg",
"price": 5000,
"top": true
},
{
"code": "DT4235",
"name": "矽細米黃 Sabbia",
"en": "Dekton 燒結石（超薄岩板）　興立富台灣色卡　型號：DT4235 (0.4cm), DT4235 (0.8cm), DT235　官網未標價，暫定 5,000 元/才",
"brand": "帝通石 Dekton",
"series": "燒結石",
"hex": "#c8c6bb",
"img": "swatches/dekton/dk_DT4235.jpg",
"thumb": "swatches/dekton/thumb/dk_DT4235.jpg",
"price": 5000,
"top": true
},
{
"code": "DT4236",
"name": "雲母米黃 Marmorio",
"en": "Dekton 燒結石（超薄岩板）　興立富台灣色卡　型號：DT4236 (0.4cm), DT2036 (0.8cm), DT236　官網未標價，暫定 5,000 元/才",
"brand": "帝通石 Dekton",
"series": "燒結石",
"hex": "#cdc8ba",
"img": "swatches/dekton/dk_DT4236.jpg",
"thumb": "swatches/dekton/thumb/dk_DT4236.jpg",
"price": 5000,
"top": true
},
{
"code": "DT4237",
"name": "儷石淺灰 Ceppo",
"en": "Dekton 燒結石（超薄岩板）　興立富台灣色卡　型號：DT4237 (0.4cm), DT2037, DT237　官網未標價，暫定 5,000 元/才",
"brand": "帝通石 Dekton",
"series": "燒結石",
"hex": "#87847f",
"img": "swatches/dekton/dk_DT4237.jpg",
"thumb": "swatches/dekton/thumb/dk_DT4237.jpg",
"price": 5000,
"top": true
},
{
"code": "DT3001",
"name": "白金木紋 Ariane",
"en": "Dekton 燒結石（超薄岩板）　興立富台灣色卡　型號：DT3001 (0.8cm), DT301, DT8301 (2.0cm)　官網未標價，暫定 5,000 元/才",
"brand": "帝通石 Dekton",
"series": "燒結石",
"hex": "#ced1d5",
"img": "swatches/dekton/dk_DT3001.jpg",
"thumb": "swatches/dekton/thumb/dk_DT3001.jpg",
"price": 5000,
"top": true
},
{
"code": "DT4302",
"name": "金輪白 Zenith",
"en": "Dekton 燒結石（超薄岩板）　興立富台灣色卡　型號：DT4302 (0.4cm), DT3002 (0.8cm), DT302, DT8302 (2.0cm)　官網未標價，暫定 5,000 元/才",
"brand": "帝通石 Dekton",
"series": "燒結石",
"hex": "#f7f8f3",
"img": "swatches/dekton/dk_DT4302.jpg",
"thumb": "swatches/dekton/thumb/dk_DT4302.jpg",
"price": 5000,
"top": true
},
{
"code": "DT4303",
"name": "極光白 Aura",
"en": "Dekton 燒結石（超薄岩板）　興立富台灣色卡　型號：DT4303, DT3003 (0.8cm), DT303　官網未標價，暫定 5,000 元/才",
"brand": "帝通石 Dekton",
"series": "燒結石",
"hex": "#cdcac5",
"img": "swatches/dekton/dk_DT4303.jpg",
"thumb": "swatches/dekton/thumb/dk_DT4303.jpg",
"price": 5000,
"top": true
},
{
"code": "DT3006",
"name": "白鴿石 Opera",
"en": "Dekton 燒結石（超薄岩板）　興立富台灣色卡　型號：DT3006 (0.8cm)　官網未標價，暫定 5,000 元/才",
"brand": "帝通石 Dekton",
"series": "燒結石",
"hex": "#efeeea",
"img": "swatches/dekton/dk_DT3006.jpg",
"thumb": "swatches/dekton/thumb/dk_DT3006.jpg",
"price": 5000,
"top": true
},
{
"code": "DT3012",
"name": "金泥石 Laurent",
"en": "Dekton 燒結石（超薄岩板）　興立富台灣色卡　型號：DT3012 (0.8cm), DT312　官網未標價，暫定 5,000 元/才",
"brand": "帝通石 Dekton",
"series": "燒結石",
"hex": "#292726",
"img": "swatches/dekton/dk_DT3012.jpg",
"thumb": "swatches/dekton/thumb/dk_DT3012.jpg",
"price": 5000,
"top": true
},
{
"code": "DT314",
"name": "柔灰石 Liquid Embers",
"en": "Dekton 燒結石（超薄岩板）　興立富台灣色卡　型號：DT314　官網未標價，暫定 5,000 元/才",
"brand": "帝通石 Dekton",
"series": "燒結石",
"hex": "#25282b",
"img": "swatches/dekton/dk_DT314.jpg",
"thumb": "swatches/dekton/thumb/dk_DT314.jpg",
"price": 5000,
"top": true
},
{
"code": "DT315",
"name": "柔雲石 Liquid Sky",
"en": "Dekton 燒結石（超薄岩板）　興立富台灣色卡　型號：DT315　官網未標價，暫定 5,000 元/才",
"brand": "帝通石 Dekton",
"series": "燒結石",
"hex": "#e5e2dd",
"img": "swatches/dekton/dk_DT315.jpg",
"thumb": "swatches/dekton/thumb/dk_DT315.jpg",
"price": 5000,
"top": true
},
{
"code": "DT4316",
"name": "舜白石 Rem",
"en": "Dekton 燒結石（超薄岩板）　興立富台灣色卡　型號：DT4316 (0.4cm), DT3016 (0.8cm), DT316　官網未標價，暫定 5,000 元/才",
"brand": "帝通石 Dekton",
"series": "燒結石",
"hex": "#edeeea",
"img": "swatches/dekton/dk_DT4316.jpg",
"thumb": "swatches/dekton/thumb/dk_DT4316.jpg",
"price": 5000,
"top": true
},
{
"code": "DT3017",
"name": "優妮白 Uyuni",
"en": "Dekton 燒結石（超薄岩板）　興立富台灣色卡　型號：DT3017 (0.8cm), DT317　官網未標價，暫定 5,000 元/才",
"brand": "帝通石 Dekton",
"series": "燒結石",
"hex": "#f6f7f1",
"img": "swatches/dekton/dk_DT3017.jpg",
"thumb": "swatches/dekton/thumb/dk_DT3017.jpg",
"price": 5000,
"top": true
},
{
"code": "DT4318",
"name": "風絮銀 Neural",
"en": "Dekton 燒結石（超薄岩板）　興立富台灣色卡　型號：DT4318 (0.4cm), DT318　官網未標價，暫定 5,000 元/才",
"brand": "帝通石 Dekton",
"series": "燒結石",
"hex": "#f0eeec",
"img": "swatches/dekton/dk_DT4318.jpg",
"thumb": "swatches/dekton/thumb/dk_DT4318.jpg",
"price": 5000,
"top": true
},
{
"code": "DT319",
"name": "藏白霜 Daze",
"en": "Dekton 燒結石（超薄岩板）　興立富台灣色卡　型號：DT319, DT319　官網未標價，暫定 5,000 元/才",
"brand": "帝通石 Dekton",
"series": "燒結石",
"hex": "#efeeeb",
"img": "swatches/dekton/dk_DT319.jpg",
"thumb": "swatches/dekton/thumb/dk_DT319.jpg",
"price": 5000,
"top": true
},
{
"code": "DT3020",
"name": "皓月霜 Morpheus",
"en": "Dekton 燒結石（超薄岩板）　興立富台灣色卡　型號：DT3020 (0.8cm), DT320　官網未標價，暫定 5,000 元/才",
"brand": "帝通石 Dekton",
"series": "燒結石",
"hex": "#e0e0dd",
"img": "swatches/dekton/dk_DT3020.jpg",
"thumb": "swatches/dekton/thumb/dk_DT3020.jpg",
"price": 5000,
"top": true
},
{
"code": "DT4321",
"name": "玄武磁 Somnia",
"en": "Dekton 燒結石（超薄岩板）　興立富台灣色卡　型號：DT4321 (0.4cm)　官網未標價，暫定 5,000 元/才",
"brand": "帝通石 Dekton",
"series": "燒結石",
"hex": "#212121",
"img": "swatches/dekton/dk_DT4321.jpg",
"thumb": "swatches/dekton/thumb/dk_DT4321.jpg",
"price": 5000,
"top": true
},
{
"code": "DT4322",
"name": "緹焰凰 Reverie",
"en": "Dekton 燒結石（超薄岩板）　興立富台灣色卡　型號：DT4322 (0.4cm), DT3022 (0.8cm), DT322　官網未標價，暫定 5,000 元/才",
"brand": "帝通石 Dekton",
"series": "燒結石",
"hex": "#dad7d2",
"img": "swatches/dekton/dk_DT4322.jpg",
"thumb": "swatches/dekton/thumb/dk_DT4322.jpg",
"price": 5000,
"top": true
},
{
"code": "NL1240",
"name": "象牙白 Avorio",
"en": "Neolith 素色　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "素色",
"hex": "#dde0c1",
"img": "swatches/neolith/nl_NL1240.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1240.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1259",
"name": "香檳 Barro",
"en": "Neolith 素色　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "素色",
"hex": "#6a6964",
"img": "swatches/neolith/nl_NL1259.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1259.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1245",
"name": "銀灰 Cement",
"en": "Neolith 素色　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "素色",
"hex": "#7f898a",
"img": "swatches/neolith/nl_NL1245.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1245.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1272",
"name": "朱古麗 Chocolate",
"en": "Neolith 素色　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "素色",
"hex": "#524a48",
"img": "swatches/neolith/nl_NL1272.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1272.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1252",
"name": "極地黑 Nero",
"en": "Neolith 素色　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "素色",
"hex": "#2d2d2d",
"img": "swatches/neolith/nl_NL1252.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1252.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1254",
"name": "波斯灰 Phedra",
"en": "Neolith 素色　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "素色",
"hex": "#bab7ac",
"img": "swatches/neolith/nl_NL1254.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1254.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1239",
"name": "霜白 Arctic White",
"en": "Neolith 素色　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "素色",
"hex": "#fdfdf3",
"img": "swatches/neolith/nl_NL1239.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1239.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1297",
"name": "夏羽松 Summer Dala",
"en": "Neolith 木紋　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "木紋",
"hex": "#bfac9a",
"img": "swatches/neolith/nl_NL1297.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1297.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1251",
"name": "La Bohème B01 櫻桃木B01 La Bohème B01 櫻桃木B01",
"en": "Neolith 木紋　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "木紋",
"hex": "#8d7156",
"img": "swatches/neolith/nl_NL1251.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1251.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1246",
"name": "棕鐵 Iron Corten",
"en": "Neolith 鐵銹感　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "鐵銹感",
"hex": "#4a3a30",
"img": "swatches/neolith/nl_NL1246.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1246.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1237",
"name": "亞銅鐵 Iron Moss",
"en": "Neolith 鐵銹感　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "鐵銹感",
"hex": "#474444",
"img": "swatches/neolith/nl_NL1237.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1237.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1260",
"name": "白金鐵 Iron Frost",
"en": "Neolith 鐵銹感　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "鐵銹感",
"hex": "#ececec",
"img": "swatches/neolith/nl_NL1260.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1260.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1307",
"name": "史塔克鋼 Metropolitan",
"en": "Neolith 鐵銹感　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "鐵銹感",
"hex": "#2e2926",
"img": "swatches/neolith/nl_NL1307.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1307.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1278",
"name": "斑彩石 Retrostone",
"en": "Neolith 磨石子　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "磨石子",
"hex": "#ded5c8",
"img": "swatches/neolith/nl_NL1278.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1278.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1288",
"name": "木榴石 Terrazzo Ceppo",
"en": "Neolith 磨石子　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "磨石子",
"hex": "#b7b2af",
"img": "swatches/neolith/nl_NL1288.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1288.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1304",
"name": "覓石林 Shilin",
"en": "Neolith 磨石子　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "磨石子",
"hex": "#c2c0b1",
"img": "swatches/neolith/nl_NL1304.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1304.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1306",
"name": "尋武隆 Wulong",
"en": "Neolith 磨石子　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "磨石子",
"hex": "#908881",
"img": "swatches/neolith/nl_NL1306.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1306.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1257",
"name": "貝頓灰 Beton",
"en": "Neolith 清水模　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "清水模",
"hex": "#8c877a",
"img": "swatches/neolith/nl_NL1257.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1257.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1284",
"name": "紐約咖啡 New York-New York",
"en": "Neolith 清水模　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "清水模",
"hex": "#a9a6a0",
"img": "swatches/neolith/nl_NL1284.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1284.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1319",
"name": "夜來香 Niagara",
"en": "Neolith 深色系　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "深色系",
"hex": "#090909",
"img": "swatches/neolith/nl_NL1319.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1319.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1279",
"name": "瑪瑙黑 Krater",
"en": "Neolith 深色系　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "深色系",
"hex": "#4e4846",
"img": "swatches/neolith/nl_NL1279.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1279.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1244",
"name": "玄黑 Basalt Black",
"en": "Neolith 深色系　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "深色系",
"hex": "#282d32",
"img": "swatches/neolith/nl_NL1244.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1244.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1258",
"name": "古典黑 Belgian Blue",
"en": "Neolith 深色系　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "深色系",
"hex": "#1f2129",
"img": "swatches/neolith/nl_NL1258.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1258.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1255",
"name": "織紡黑 Textil Black",
"en": "Neolith 深色系　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "深色系",
"hex": "#474b49",
"img": "swatches/neolith/nl_NL1255.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1255.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1277",
"name": "亞斯本灰 Aspen Grey",
"en": "Neolith 深色系　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "深色系",
"hex": "#5c5450",
"img": "swatches/neolith/nl_NL1277.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1277.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1281",
"name": "拉托淺黑 Calatorao",
"en": "Neolith 深色系　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "深色系",
"hex": "#36342f",
"img": "swatches/neolith/nl_NL1281.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1281.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1295",
"name": "輝夜黑 Layla",
"en": "Neolith 深色系　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "深色系",
"hex": "#1a1a1a",
"img": "swatches/neolith/nl_NL1295.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1295.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1298",
"name": "撒哈拉黑 Sahara Noir",
"en": "Neolith 深色系　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "深色系",
"hex": "#0e0c0c",
"img": "swatches/neolith/nl_NL1298.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1298.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1285",
"name": "三月河 Mar del Plata",
"en": "Neolith 深色系　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "深色系",
"hex": "#7c7773",
"img": "swatches/neolith/nl_NL1285.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1285.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1294",
"name": "金荷綠 Amazonico",
"en": "Neolith 深色系　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "深色系",
"hex": "#4d4c47",
"img": "swatches/neolith/nl_NL1294.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1294.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1267",
"name": "卡拉卡白 Calacatta",
"en": "Neolith 淺色系　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "淺色系",
"hex": "#f7f9f2",
"img": "swatches/neolith/nl_NL1267.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1267.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1236",
"name": "卡拉卡金 Calacatta Gold",
"en": "Neolith 淺色系　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "淺色系",
"hex": "#f0efeb",
"img": "swatches/neolith/nl_NL1236.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1236.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1269",
"name": "灰彩石 Estatuario",
"en": "Neolith 淺色系　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "淺色系",
"hex": "#f8faf4",
"img": "swatches/neolith/nl_NL1269.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1269.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1292",
"name": "光耀白金 Abu Dhabi White",
"en": "Neolith 淺色系　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "淺色系",
"hex": "#e6e5e4",
"img": "swatches/neolith/nl_NL1292.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1292.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1289",
"name": "華美石 Calacatta Luxe",
"en": "Neolith 淺色系　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "淺色系",
"hex": "#dddbd8",
"img": "swatches/neolith/nl_NL1289.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1289.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1293",
"name": "雪玉白石 Himalaya Crystal",
"en": "Neolith 淺色系　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "淺色系",
"hex": "#d9d8d4",
"img": "swatches/neolith/nl_NL1293.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1293.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1300",
"name": "琉璃金石 New Gold",
"en": "Neolith 淺色系　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "淺色系",
"hex": "#b3aeaa",
"img": "swatches/neolith/nl_NL1300.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1300.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1312",
"name": "古典白 Alexandra",
"en": "Neolith 淺色系　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "淺色系",
"hex": "#c3c3c3",
"img": "swatches/neolith/nl_NL1312.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1312.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1313",
"name": "皇家白 Calacatta Royale",
"en": "Neolith 淺色系　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "淺色系",
"hex": "#f0f0ee",
"img": "swatches/neolith/nl_NL1313.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1313.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1315",
"name": "砂丘白 Colorado Dunes",
"en": "Neolith 淺色系　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "淺色系",
"hex": "#cfc9b1",
"img": "swatches/neolith/nl_NL1315.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1315.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1316",
"name": "喜夢白 San Simone",
"en": "Neolith 淺色系　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "淺色系",
"hex": "#d3cec7",
"img": "swatches/neolith/nl_NL1316.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1316.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1320",
"name": "藤花白 Arabesque",
"en": "Neolith 淺色系　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "淺色系",
"hex": "#cdcdcd",
"img": "swatches/neolith/nl_NL1320.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1320.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1243",
"name": "熔岩米黃 Arena",
"en": "Neolith 淺色系　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "淺色系",
"hex": "#eae2cc",
"img": "swatches/neolith/nl_NL1243.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1243.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1275",
"name": "卡拉白中花 Blanco Carrara BC02",
"en": "Neolith 淺色系　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "淺色系",
"hex": "#e6e6e6",
"img": "swatches/neolith/nl_NL1275.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1275.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1286",
"name": "白朗石 Mont Blanc",
"en": "Neolith 淺色系　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "淺色系",
"hex": "#e8e7e5",
"img": "swatches/neolith/nl_NL1286.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1286.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1299",
"name": "天磯銀 Super White",
"en": "Neolith 淺色系　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "淺色系",
"hex": "#bdbdba",
"img": "swatches/neolith/nl_NL1299.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1299.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1280",
"name": "瑪瑙銀 Strata Argentum",
"en": "Neolith 淺色系　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "淺色系",
"hex": "#cac9c7",
"img": "swatches/neolith/nl_NL1280.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1280.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1276",
"name": "銀紋灰 Zaha Stone",
"en": "Neolith 灰色系　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "灰色系",
"hex": "#939693",
"img": "swatches/neolith/nl_NL1276.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1276.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1242",
"name": "玄灰 Basalt Grey",
"en": "Neolith 灰色系　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "灰色系",
"hex": "#666a66",
"img": "swatches/neolith/nl_NL1242.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1242.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1309",
"name": "銀河灰 Galaxy Grey",
"en": "Neolith 灰色系　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "灰色系",
"hex": "#a29f97",
"img": "swatches/neolith/nl_NL1309.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1309.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1301",
"name": "Estatuario Lobby 灰彩石Lobby系列 Estatuario Lobby 灰彩石Lobby系列",
"en": "Neolith 石紋　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "石紋",
"hex": "#f8f8f8",
"img": "swatches/neolith/nl_NL1301.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1301.jpg",
"price": 4800,
"top": true
},
{
"code": "NL1261",
"name": "波麗咖啡 Pulpis",
"en": "Neolith 石紋　燒結石（超薄岩板）　興立富台灣色卡　官網未標價，暫定 4,800 元/才",
"brand": "耐麗石 Neolith",
"series": "石紋",
"hex": "#4a392a",
"img": "swatches/neolith/nl_NL1261.jpg",
"thumb": "swatches/neolith/thumb/nl_NL1261.jpg",
"price": 4800,
"top": true
}
]);
